-- Mass gap: machine-checked arithmetic core of research/PAPER.md
import MassGap.Floor      -- Sec 7: entropy floor kappa_0 = (1/4) log 3 > 0 and its density limit
import MassGap.Bounds     -- Sec 3/9: Strehl bound rho'(1)^2 <= 1; Ising transfer rho'(1) = tanh b < 1
import MassGap.Running    -- Sec 5: asymptotic freedom b0,b1>0 => beta<0 => no interior fixed point
import MassGap.ReachFreeze  -- Sec 6: contraction c>0 => exp decay => a_IR=0 => Delta>=c>0 (reach-freeze)
import MassGap.Aperture   -- Sec 4/6: finite aperture => dichotomy; F-uniform; no interior transition; a->0
import MassGap.Forgetting     -- Sec 4/6: the six faces of forgetting; margin => decay+summable+Lambda; foil
import MassGap.Certify    -- certified mu<kappa_0 (contrast criterion + finite-correlation-length crossover) => the gap
import MassGap.Bessel     -- C-2: modified Bessel series => I_n(x)>0 for x>0 => r=I2/I1>0 (ym_ratio_pos, no axiom)
import MassGap.Existence  -- Sec 11: reflection positivity survives the continuum limit (no transfer matrix)
import MassGap.Apriori    -- THE a priori: A1 (confinement) + A2 (isotropy) => the result
import MassGap.Model      -- Phase 0: lattice YM model interface; A1/A2 as typed obligations
import MassGap.Complete   -- Path 1: discharge A1+A2 from four named standard axioms => gap, no hypothesis
import MassGap.GapRate    -- bridge: the mass gap Delta = kappa_0 - mu (entropy margin) => quantitative exp decay at rate Delta
import MassGap.MinEntropy   -- the entropy map: tension mu = min-entropy deficit; noise floor as an entropy object (no axiom)
import MassGap.FreeField     -- free-field weak end: mu_inf = 2.1/L^2 -> 0 < kappa_0 (Wick), discharges apriori_A1_weak (no axiom)
import MassGap.Measure       -- continuum measure (reading A): gap => bounded resolved dim => tightness of the a->0 limit (no axiom)
import MassGap.FullModel          -- bridge: FullModel => existence_and_gap_of_model (mass gap AND OS measure) + wightman_of_model (link to cited OS/Wightman reconstruction)
import MassGap.Reconstruction -- OS reconstruction, operator core: GNS separation (RP form => definite inner product) + H = -log T self-adjoint, >= 0, vacuum at 0, spec H in {0} u [Delta,inf) (reconstruct_qm_core, CFC)
import MassGap.GappedTheory   -- the reconstructed gapped quantum theory as DATA: structure GappedQuantumTheory (H, gap, self-adjoint, >=0, vacuum, spectral gap) produced by reconstruct_gapped
import MassGap.GappedExample -- a CONCRETE gapped quantum theory: diag(1, 3^{-1/4}) on ℂ², gap κ₀=¼log3 discharged BY COMPUTATION (concreteGapped)
import MassGap.MomentSupport  -- the moment-support lemma: positive-weight decay ∑ w_k λ_k^τ ≤ M ρ^τ ⇒ each w_k>0 mode has λ_k ≤ ρ (the C(τ)→0 ⇒ spectral-support step)
import MassGap.ScreenedGap
import MassGap.WilsonHypercubic
import MassGap.ZeroMode     -- the tension KILLS the zero mode: a constant contributes 0 to the circular first moment, so mu<kappa_0 bounds c*(N+1) and the aperture limit forces c=0
import MassGap.WilsonBridge  -- THE JOIN: the entropy read applied to the constructed SU(N) Wilson correlation, not an opaque one
import MassGap.GapOfDecay     -- wire: DERIVE hsp from the connected-correlator decay (MomentSupport) + RP ⇒ reconstruct the gapped theory; gap = decay rate, foundational axioms only
import MassGap.YMGap          -- YM instantiation: confinement (ΔYM=κ₀−μ>0) ⇒ (bridge) ⇒ GappedQuantumTheory with spectrum(H)⊆{0}∪[Δ,∞); same axiom footprint as the reduction, no new axioms
import MassGap.Margin   -- A1 junction: aperture margin from κ₀≤κ (Floor) + c≤Δ (reach-freeze) + one junction κ−μ≤c; the read margin DERIVED, not postulated
import MassGap.Mixing         -- A1 via ρ'(1): S1 (ρ'(1)<1 ⇒ gap, volume-uniform by RP) + S3 (interior ρ'(1)<1 from analyticity + finite grid)
import MassGap.Interior       -- supplies the substrate bound on a compact coupling interval, from finite-volume analyticity (DifferentiableAt) + a finite grid
import MassGap.Condensation   -- R2: below the floor the vortex sum diverges — condensation ⟺ μ<κ₀, from Thm 7.1's count (proved); per-step log-increment of the lower-bound count = 4(κ₀−μ) exactly
import MassGap.CentreDominance -- R3b assembly: area beats perimeter (P/A→0) ⇒ σ_SU(N)=σ_Z
import MassGap.WilsonInstance   -- residual A: a CONSTRUCTED SU(N) FullModel ⇒ both parts (ym_existence_and_gap_model, footprint = 4 named axioms) + Wightman QFT (ym_wightman, all 6) on a concrete object, no new axiom
import MassGap.CellEnclosure  -- Path 2 / B1 (WIP toward removing the external single-cell certificate): the single-plaquette Kogut–Susskind Hamiltonian in exact rationals; so far Hcell + symmetry + cell_clears_floor + twoState_gap_clears_floor; the Feshbach tail lifting a truncation to the true single-cell gap ≥ κ₀ is the remaining piece
import MassGap.CellSpectrum   -- Path 2 / B1 spectral core (foundation-only footprint): the eigenbasis dotProduct bridges; atMostOne_eigenvalue_lt (the min-max count lemma Mathlib lacks: form ≥ μ on a corank-≤1 subspace ⇒ ≤1 eigenvalue < μ); eigenvalues_gap_of_codim1_form (that + a ground eigenvalue ≤ 0 ⇒ spectrum ⊆ {E₀}∪[E₀+κ₀,∞)); and axiom-free single-cell gaps built with it: Hcell2 (2-state, dominant j∈{0,½} truncation) COMPLETE for all λ (Hcell2_gap, Hcell2_clears_floor ⇒ ρ'(1)=m_cell ≤ 3^{−1/4} < 1), and Hcell3 (3-state). Plus the U2 (spatial-volume) close, all foundation-only: gap_uniform_of_cell (wires Mixing S1 — RP ⇒ ρ'(n)=ρ'(1)^n exactly, one cut controls every volume) and gap_uniform_of_cell_intensive (intensive input ∀F m_hi(F) ≤ 3^{−1/4} ⇒ volume-uniform gap, radius pinned to the machine-checked cell ceiling); read_margin_of_gap_ge_floor/Hcell2_read_margin (discharge the Margin bridge's c≤Δ/κ₀−μ≤c at the single cell); and the capstone ym_volume_gap_cell_grounded (the U2 reduction on the actual YM modes). The intensive input is the measured continuum read (Entroptics volume sweep, _scratch/U2-CLOSE.md).
import MassGap.Capacity       -- Step 2 wiring: the flagship WITHOUT the definitional witness — hread DERIVED for FREE modes from the two named residuals (κ−μ≤c, c≤Δ) + the proved floor; foundation-only (hread_of_junction, existence_and_gap_of_junction)
import MassGap.LatticeGauge    -- residual A / step A1: a genuine finite lattice gauge measure over a compact group; the OS invariances DERIVED from Haar-invariance ∘ plaquette-permutation (Symmetry.expect_invariant : ⟨O∘reindex⟩=⟨O⟩), NOT rfl; foundation-only
import MassGap.CompactGauge    -- step A2a: compact Hausdorff Borel group ⇒ canonical probability Haar (probHaar); the A1 measure DERIVED (not assumed); expect_invariant_haar, foundation-only
import MassGap.SUN             -- step A2b: the compact topological-group + Borel instances for SU(N)=specialUnitaryGroup (Fin n) ℂ (Nonempty, IsTopologicalGroup, CompactSpace via closed∩Tychonoff, BorelSpace); su_expect_invariant lands the derived invariance on the real SU(N) Haar measure; foundation-only
import MassGap.WilsonGauge     -- step A3: ymFamilyGauge — an OS-data family whose reflected form is a genuine SU(2) Haar expectation and whose os_euc/os_perm are DERIVED via Symmetry.expect_invariant (not rfl); WilsonGauge.ym_continuum_gauge (OS0–OS3 continuum measure, FOUNDATIONAL) + ym_existence_and_gap_gauge (gap+measure, same 4 named axioms — all on the gap side, measure side axiom-free)
import MassGap.WilsonAction    -- dynamical face (brick 1): the genuine Wilson action density φ_W(g)=1−(1/N)Re tr g on SU(N); wilsonDensity_one (zero at identity) + wilsonDensity_conj (gauge-invariance seed, from trace cyclicity); foundation-only
import MassGap.WilsonLattice   -- dynamical face (brick 2): real plaquette holonomy = ordered loop product (boundary word of (link,orientation)); wilsonSystem + wilsonSymmetry (compat = List.map/prod reindexing, the "lattice rotation permutes plaquettes" content) + wilson_expect_invariant (A1 payoff on a real action); foundation-only
import MassGap.WilsonReal      -- dynamical face (brick 2b): a CONCRETE SU(2) two-plaquette Wilson system (genuine 4-link loops, real wilsonDensity action) with a ℤ/2 plaquette-swap symmetry (hbd2 by decide); sysReal_invariant = Euclidean/permutation invariance of the real Wilson correlation, derived; foundation-only
import MassGap.ReflectionPositivity  -- the MECHANISM of reflection positivity: a positive-half function paired with its own reflection integrates to a square (proved); the cited half is writing the Wilson weight in paired form
import MassGap.CellPivot     -- GENERATED (certify/cell_pivot_certificate.py --emit-lean): the exact-rational pivot certificate in full, transcribed and kernel-checked at jmax=4, dim=9 — all 61 certified couplings on λ ∈ [0.16, 6.76], 17 by the ABSOLUTE route (one negative pivot ⇒ E₁ ≥ μ outright) and 44 by the RELATIVE one (Sturm shift below E₁, trial vector above E₀), every one foundation-only
import MassGap.CellPerturb  -- the cover, WITHOUT a Weyl inequality: `Hcell` depends on λ only through its 0/1 nearest-neighbour adjacency (HcellR_sub_smul_adj), whose form is bounded by 2‖v‖² by AM-GM against the row and column sums (adj_form_bound) — so the cell's QUADRATIC FORM is Lipschitz in the coupling (HcellR_form_lipschitz). Both spectral inputs the certificate uses are already form-stated (exists_eigenvalue_le_of_form, atMostOne_eigenvalue_lt), so the two transport lemmas cell_form_le_of_form_le and cell_form_ge_of_form_ge carry a certificate to a NEIGHBOURING coupling with no eigenvalue perturbation anywhere — one lemma per eigenvalue, which is where the certificate's LIPSCHITZ = 4 comes from (2 each). Foundation-only.
import MassGap.CellCover   -- GENERATED (--emit-lean-cover): the coupling range as an INTERVAL rather than a grid. 19 anchors, each carrying its own certificate and an EARNED radius (certified - kappa_0)/4, chained into `cell_gap_on_range`: for EVERY rational lambda in [0.16, 6.76] the cell has a spectral gap at least kappa_0's certified upper bound. The walk takes whichever route earns the larger radius at each step, which is why 19 anchors suffice where two separate walks took 75. Foundation-only.
import MassGap.CellTail     -- the TRUNCATION TAIL, bounded rather than dropped: the backward pivot recurrence is monotone in its seed (pivotSeqFrom_mono), so seeding it with a LOWER BOUND on the cell's true pivot at the last index bounds every pivot below (pivotSeqFrom_mono_above, pos_above_of_tail). Truncation drops a subtraction and is therefore OPTIMISTIC; this is what makes the certificate a statement about the cell rather than about its truncation. The arithmetic side (a self-consistent eps with eps*(d(m+1)-s-eps) >= lam^2, closing at m<=6 across the crossover) is certify/cell_pivot_certificate.tail_start; foundation-only
import MassGap.VortexCount     -- dynamical face (brick 3 / B): the count-injection at the Floor-EXACT constant — junction_of_floor_count derives κ₀−μ≤c from a physical vortex weight dominating the machine-checked directed_surface_count (3^k at area 4k+6, NOT the loose 3^n vortexTerm); floor_count_injection ties the injection LHS to directed_surface_count; density (k·log3)/(4k+6)→κ₀ proved; foundation-only
import MassGap.HaarMoments      -- strong-coupling workhorse (milestone 1 toward nontrivial clustering): ∫_{SU(2)} U_ij dHaar = 0 (haar_su2_coeff_zero) — fundamental-rep matrix coefficients Haar-average to zero, from left-invariance ∘ the single diagonal element diag(i,-i) (invariant-projection, no Peter–Weyl); the FULL Schur orthogonality tensor ∫U_ij Ū_kl = ½δ_ik δ_jl (haar_su2_second_moment), character norm ∫|tr U|²=1 (haar_su2_char_norm), and two-point engine ∫tr(UA)tr(U*B)=½tr(AB) (haar_su2_two_point) — all by explicit-element invariance, no Peter–Weyl; foundation-only
import MassGap.InteractingTwoPoint -- milestone 3 capstone: the first NON-FACTORIZING correlation on the interacting lattice — sysInt's two plaquettes share link 3, and ∫ tr(hol₀)tr(hol₁) dU₃ = ½ tr(C₀C₁) (sysInt_shared_link_two_point) via haar_su2_shared_link (product of marginals = 0, joint ≠ 0 because they share the link); the ⟨φ_p φ_q⟩_c ≠ 0 mechanism, foundation-only
import MassGap.WitnessVacuity  -- P1 guard: imports Mathlib ONLY (no MassGap module in scope). const_witness_conclusion_is_arithmetic reproduces the RETIRED ym_mass_gap_spectral's conclusion (m ≡ 1/5, P ≡ 1) from arithmetic alone, so that statement carried no gauge content whatever its footprint read; aperture_hypothesis_is_load_bearing exhibits a mode of magnitude 2 whose correlator diverges, so the REPLACEMENT cannot drop hmargin/haperture. Checks in Lean what was previously only asserted in prose.
import MassGap.WilsonRead     -- the entropy-matched read applied to a GENUINE Wilson Gibbs correlation on sysReal (8 links, 2 real ordered-loop plaquettes, real Wilson action, Haar). UNCONDITIONAL: wilsonCorrReal_nonneg DERIVES the nonnegativity that `Complete.wilson_reflection_positive` asserts for the opaque ensemble, and sum_wilsonCorrReal_pos DERIVES the positive total mass -- via expect_ge_haar_of_nonneg (Gibbs dominates Haar by e^{-8|beta|}, so beta drops out) and integral_re_trace_hol_zero (the Z2 CENTRE: translating one link by -1 negates the holonomy, so the character integral equals minus itself). No axiom, no hypothesis; foundational footprint.
import MassGap.WilsonAnalytic -- finite-volume analyticity in beta, and THE COVARIANCE IDENTITY d<O>_beta/dbeta = -Cov_beta(O,S), PROVED on the genuine Wilson Gibbs measure by differentiation under the integral (dominated by a CONSTANT, since the action is bounded in [0,4]) plus the quotient rule with Z>0. This is the fact Interior.lean states in prose and never proves, and it discharges Interior's `hdiff` hypothesis. Settles the finite-volume half of the RG/no-bulk-transition route exactly: no non-analyticity anywhere on the real beta axis at finite volume. It also GENERALISES that identity off the two-plaquette instance to an arbitrary SU(N) Wilson system, so the plaquette count is explicit, and then settles what Cov costs: `cov_bound_extensive` proves the assumption-free bound really is O(#Plaq) (Popoviciu-grade, the obstruction, machine-checked), while `cov_eq_sum_over_plaquettes` + `cov_sum_bound_of_local` prove the sum is bounded by its SUPPORT, giving `cov_bound_local` |Cov(O,S)| <= 4*M*|supp| with no volume in it. `expect_lipschitz_local` turns that into a volume-independent Lipschitz constant and `wilson_le_uniform_in_volume` runs it through the grid lemma, yielding <O>_beta <= B on [a,b] at EVERY volume with the SAME constants. Clustering -- that the connected plaquette correlator has a volume-independent reach -- is now the single open input; it is not assumed here and not vacuous (WilsonReal.expect_plaqObs_factor makes it hold outright on disjoint plaquettes, InteractingTwoPoint exhibits a nonzero connected pair). Foundational footprint.
import MassGap.StrongCoupling -- the RESUMMATION between a connected pair and a decaying bound: the analytic half of a strong-coupling cluster expansion, proved — the per-plaquette Boltzmann weight |e^{-beta*phi}-1| <= e^{2|beta|}-1 (boltz_factor_bound, from phi in [0,2]), the geometric resummation of chains of length >= d (decay_of_chain_bound), and the threshold beta < log(1+1/K)/2 at which the rate K(e^{2beta}-1) drops below one (chain_rate_lt_one) — all foundation-only. The COMBINATORIAL half is named `ChainBound` and is NOT proved: that the connected correlation really is dominated by a chain sum is where the VOLUME CANCELS, which is the whole content of a cluster expansion. Discharging it makes Complete.ym_mass_gap_of_lag_decay unconditional below the threshold; it does not reach the continuum, where the expansion diverges.
