import Mathlib
import MassGap.ReflectionStrong
import MassGap.WilsonTransfer

/-!
# MassGap.OSPositivity — the Osterwalder–Schrader positivity clause, closed as far as this lattice allows

`ReflectionStrong` proved `0 ≤ ⟨F · (F ∘ Θ)⟩` for every real bounded measurable observable of the
slab, at every real coupling, and listed six things separating that from OS3. This file closes the
three of those six that are closable at a finite periodic lattice — complex sesquilinearity, the
algebra clause, and the time translation as an operator — and names the remainder as `Prop`s rather
than as prose.

## What is proved here, in OS3's own vocabulary

Write `Θ = Reflect.reflConf τ (a + a)` for the site reflection, `⟨·⟩` for the genuine Wilson Gibbs
expectation `ReflectPositive.EW N β` at a lattice of even extent `n = 2m`, and

    𝔄 = LogConvex.localObs (blkS τ a m) (blkR τ a m)

for the module of bounded measurable observables determined by the slab and its two bounding planes.

1. **Sesquilinear positivity on the diagonal.** For every `ℂ`-valued observable `F` whose real and
   imaginary parts both lie in `𝔄` (`localObsC`),

       0 ≤ ⟨ conj(F ∘ Θ) · F ⟩      and      ⟨ conj(F ∘ Θ) · F ⟩ is REAL

   — `wilson_osC_diag_re_nonneg` and `wilson_osC_diag_im_zero`, each a statement about ONE Gibbs
   expectation of the genuine complex OS pairing, at every real `β`. The complex pairing itself is
   `cform`, and `cform_eq_osPairing` proves `cform` equals the expectation of `conj(F ∘ Θ) · G`
   componentwise, so the abstract complexification below is that expectation and not an analogue of
   it.

2. **Sesquilinearity and the complex Gram matrix.** `cform_conj_symm`, `cform_add_left`,
   `cform_smul_left` (conjugate-linear in the reflected slot), `cform_add_right`, `cform_smul_right`
   (linear in the other), and `cform_gram_re_nonneg` / `cform_gram_im_zero`: for every finite family
   of complex test observables and every family of COMPLEX coefficients, `∑ᵢⱼ conj(cᵢ) cⱼ ⟨θF̄ᵢ·Fⱼ⟩`
   is a nonnegative real. That is OS3's matrix inequality, sesquilinear, at finite volume.

3. **The algebra clause.** `𝔄` is a unital subalgebra (`ReflectionStrong.mul_mem_localObs`,
   `one_mem_localObs`), and `prod_mem_localObs` extends that to arbitrary finite products.
   `wilson_gram_nonneg_monomials` is the combination OS3 asks for: given ANY family of generators in
   `𝔄`, the Gram matrix over the monomials in those generators is positive semidefinite. So
   positivity holds over the algebra generated by the slab observables, not merely over a subspace of
   them.

4. **The GNS Hilbert space.** `Transfer.GNS` applied to `ReflectionStrong.wilsonGibbsReflForm` is a
   genuine `InnerProductSpace ℝ` whose inner product is the Gibbs reflection pairing
   (`slab_inner_mk`) and in which the constant observable is a unit vector (`slab_vac_norm`). This is
   what OS3 is FOR, and it is available at finite volume on the slab.

5. **The time translation.** `WilsonTransfer` already supplies the operator, its invariance
   (`expect_shift_invariant`), its self-adjointness for this very form
   (`reflForm_shiftObs_symm`) and `T_vac`. `wilsonSlabTransfer` assembles a full
   `Transfer.TransferData` on `𝔄` from exactly two named premises, `SlabShiftStable` and
   `SlabShiftContractive`, and nothing else.

## What is NOT proved here — and what is not OS3

OS3 is positive semidefiniteness of `⟨θF̄ · F⟩` over the algebra of observables supported in the
positive-time half-space of the INFINITE-VOLUME CONTINUUM Euclidean measure. Of
`ReflectionStrong`'s six separations, exactly one is closed here — "real, not complex" — one survives
only in part — "no time translation" — and the remaining four survive untouched.

* **Finite volume, finite lattice spacing, no limit.** Every statement here is at a fixed even extent
  `n = 2m` and a fixed spacing, on the periodic `sysWilson` measure. Nothing in this file's import
  closure carries an infinite-volume or continuum measure — `InfiniteVolume` takes subsequential
  limits of finite-volume NUMBERS (`corrLag : ℕ → ℝ → ℕ → ℝ`; the word `Measure` does not occur in
  it) — so there is no infinite-volume object here to quantify a `Prop` over, and none is named.
  Every theorem below is universally quantified over `τ`, `a`, `m` and `β`, which is uniformity in
  the extent, not a limit: carrying any of it to a limit measure is a separate construction and no
  part of it is claimed here.

* **A SLAB, not a half-space.** `blkS τ a m` is bounded ABOVE by the second reflection plane as well
  as below by the first, because a periodic lattice has no half-space. This is the separation that
  does not close, and `SlabShiftStable` is its operative form: the slab algebra would have to be
  stable under one lattice step for a transfer operator to exist on it.
  `WilsonTransfer.shift_not_stable_on_slab` exhibits a link that refutes stability for the support
  block, and `HalfLineTransfer.const_of_shift_stable` (not imported here) proves the stronger
  statement that every shift-stable submodule of the slab algebra consists of CONSTANT observables at
  `2 ≤ m`. So `SlabShiftStable` is named as a premise, not as a plausible one.

* **Regularity, Euclidean invariance, ergodicity.** The other Osterwalder–Schrader axioms are not
  addressed here, exactly as before. What the time-translation part of this file adds is one
  translation symmetry of the Gibbs state (`WilsonTransfer.expect_shift_invariant`), which is a
  lattice symmetry and not OS1, OS2 or OS4.

* **One family of reflections.** Everything here runs on the SITE reflection `reflConf τ (a + a)`.
  The link reflections are `OddLagSplit`'s, use a different decomposition, and genuinely need
  `0 ≤ β`. Nothing in this file touches them, and nothing in this file carries a sign condition.

The distance to OS3 after this file is the geometry, the limits, the link reflections and the other
Osterwalder–Schrader axioms. What is not in that list is the positivity itself: real and complex,
diagonal and matrix, over an algebra, with a Hilbert space built from it, at every real coupling.

Foundational footprint only (`#print axioms` at the end).
Build: `python research/code/lean_build.py build MassGap.OSPositivity`.
-/

namespace MassGap.OSPositivity

open MeasureTheory
open MassGap MassGap.Reflect MassGap.WilsonHypercubic MassGap.ReflectionPositivity
open MassGap.WilsonLattice MassGap.CompactGauge MassGap.WilsonReal MassGap.WilsonAction
open MassGap.ActionSplit MassGap.ReflectPositive MassGap.WilsonBridge MassGap.LogConvex
open MassGap.ReflectionStrong

/-! ## Part 0 — one complex extensionality step, proved from `re_add_im`

Every `ℂ`-valued identity below is settled by its two real components. This is the only place the
passage from components to the complex number itself is made.
-/

/-- Two complex numbers with equal components are equal.

DERIVED: no numeral. -/
theorem ceq {x y : ℂ} (hre : x.re = y.re) (him : x.im = y.im) : x = y := by
  rw [← Complex.re_add_im x, ← Complex.re_add_im y, hre, him]

/-! ## Part 1 — the complexification of a real reflection form

OS3 is sesquilinear on complex test functions; `Transfer.ReflForm` is real and bilinear. The passage
is the standard one: a complex test observable is a PAIR of real ones, the scalar action is complex
multiplication read on that pair, and the form is

    ⟨z, w⟩_ℂ = (⟨z₁,w₁⟩ + ⟨z₂,w₂⟩) + i(⟨z₁,w₂⟩ − ⟨z₂,w₁⟩).

Nothing here is specific to the Wilson measure: it needs symmetry and bilinearity for the algebra and
`form_nonneg` only for the final two theorems. Part 3 identifies this form with the genuine complex
Gibbs pairing, so it is that pairing and not a model of it.
-/

section Complexify

variable {A : Type*} [AddCommGroup A] [Module ℝ A]

/-- **THE COMPLEX SCALAR ACTION ON A PAIR OF REAL TEST VECTORS.** `(x + iy)·(u + iv)` read on
components, with no `Module ℂ` instance placed on `A × A`.

DERIVED: no numeral; `c.re` and `c.im` are the caller's scalar. -/
def cscal (c : ℂ) (z : A × A) : A × A :=
  (c.re • z.1 + (-c.im) • z.2, c.re • z.2 + c.im • z.1)

@[simp] theorem cscal_fst (c : ℂ) (z : A × A) :
    (cscal c z).1 = c.re • z.1 + (-c.im) • z.2 := rfl

@[simp] theorem cscal_snd (c : ℂ) (z : A × A) :
    (cscal c z).2 = c.re • z.2 + c.im • z.1 := rfl

/-- **THE COMPLEXIFIED FORM.** The real part pairs like with like; the imaginary part is the
antisymmetric cross term, which is what makes the form conjugate-symmetric rather than symmetric.

DERIVED: no numeral. -/
noncomputable def cform (P : MassGap.Transfer.PreForm A) (z w : A × A) : ℂ :=
  ((P.form z.1 w.1 + P.form z.2 w.2 : ℝ) : ℂ)
    + ((P.form z.1 w.2 - P.form z.2 w.1 : ℝ) : ℂ) * Complex.I

@[simp] theorem cform_re (P : MassGap.Transfer.PreForm A) (z w : A × A) :
    (cform P z w).re = P.form z.1 w.1 + P.form z.2 w.2 := by
  simp [cform]

@[simp] theorem cform_im (P : MassGap.Transfer.PreForm A) (z w : A × A) :
    (cform P z w).im = P.form z.1 w.2 - P.form z.2 w.1 := by
  simp [cform]

/-- **CONJUGATE SYMMETRY** — the sesquilinear replacement for `form_symm`. -/
theorem cform_conj_symm (P : MassGap.Transfer.PreForm A) (z w : A × A) :
    cform P z w = (starRingEnd ℂ) (cform P w z) := by
  refine ceq ?_ ?_
  · simp only [cform_re, Complex.conj_re]
    rw [P.form_symm w.1 z.1, P.form_symm w.2 z.2]
  · simp only [cform_im, Complex.conj_im]
    rw [P.form_symm w.1 z.2, P.form_symm w.2 z.1]
    ring

/-- Additivity in the reflected slot. -/
theorem cform_add_left (P : MassGap.Transfer.PreForm A) (z z' w : A × A) :
    cform P (z + z') w = cform P z w + cform P z' w := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.add_re, Complex.add_im, Prod.fst_add, Prod.snd_add,
      P.form_add_left] <;> ring

/-- The reflected slot at zero. -/
theorem cform_zero_left (P : MassGap.Transfer.PreForm A) (w : A × A) :
    cform P 0 w = 0 := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.zero_re, Complex.zero_im, Prod.fst_zero, Prod.snd_zero,
      P.form_zero_left] <;> ring

/-- **CONJUGATE HOMOGENEITY IN THE REFLECTED SLOT.** This is the clause that makes the form
sesquilinear rather than bilinear, and it is where the reflection's conjugation lives. -/
theorem cform_smul_left (P : MassGap.Transfer.PreForm A) (c : ℂ) (z w : A × A) :
    cform P (cscal c z) w = (starRingEnd ℂ) c * cform P z w := by
  refine ceq ?_ ?_ <;>
    simp only [cscal_fst, cscal_snd, cform_re, cform_im, Complex.mul_re, Complex.mul_im,
      Complex.conj_re, Complex.conj_im, P.form_add_left, P.form_smul_left] <;> ring

/-- Additivity in the unreflected slot. -/
theorem cform_add_right (P : MassGap.Transfer.PreForm A) (z w w' : A × A) :
    cform P z (w + w') = cform P z w + cform P z w' := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.add_re, Complex.add_im, Prod.fst_add, Prod.snd_add,
      P.form_add_right] <;> ring

/-- The unreflected slot at zero. -/
theorem cform_zero_right (P : MassGap.Transfer.PreForm A) (w : A × A) :
    cform P w 0 = 0 := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.zero_re, Complex.zero_im, Prod.fst_zero, Prod.snd_zero,
      P.form_zero_right] <;> ring

/-- **HOMOGENEITY IN THE UNREFLECTED SLOT**, with no conjugation. -/
theorem cform_smul_right (P : MassGap.Transfer.PreForm A) (c : ℂ) (z w : A × A) :
    cform P z (cscal c w) = c * cform P z w := by
  refine ceq ?_ ?_ <;>
    simp only [cscal_fst, cscal_snd, cform_re, cform_im, Complex.mul_re, Complex.mul_im,
      P.form_add_right, P.form_smul_right] <;> ring

/-- **THE DIAGONAL IS REAL.** The cross terms cancel by symmetry of the underlying real form. -/
theorem cform_diag (P : MassGap.Transfer.PreForm A) (z : A × A) :
    cform P z z = ((P.form z.1 z.1 + P.form z.2 z.2 : ℝ) : ℂ) := by
  refine ceq (by simp) ?_
  simp only [cform_im, Complex.ofReal_im]
  rw [P.form_symm z.1 z.2]
  ring

/-- **THE DIAGONAL IS NONNEGATIVE**, from `form_nonneg` on each component and nothing else.

DERIVED: the `0` of `0 ≤ …` is positive semidefiniteness itself. -/
theorem cform_diag_re_nonneg (P : MassGap.Transfer.ReflForm A) (z : A × A) :
    0 ≤ (cform P.toPreForm z z).re := by
  simp only [cform_re]
  exact add_nonneg (P.form_nonneg z.1) (P.form_nonneg z.2)

/-- The diagonal has no imaginary part. -/
theorem cform_diag_im_zero (P : MassGap.Transfer.PreForm A) (z : A × A) :
    (cform P z z).im = 0 := by
  rw [cform_diag]
  simp

/-- A complex linear combination in the reflected slot, with the coefficients conjugated. -/
theorem cform_sum_left (P : MassGap.Transfer.PreForm A) {ι : Type*} (s : Finset ι) (c : ι → ℂ)
    (z : ι → A × A) (w : A × A) :
    cform P (∑ i ∈ s, cscal (c i) (z i)) w
      = ∑ i ∈ s, (starRingEnd ℂ) (c i) * cform P (z i) w := by
  classical
  refine Finset.induction_on s ?_ ?_
  · simp only [Finset.sum_empty, cform_zero_left]
  · intro i t hi ih
    rw [Finset.sum_insert hi, Finset.sum_insert hi, cform_add_left, cform_smul_left, ih]

/-- A complex linear combination in the unreflected slot. -/
theorem cform_sum_right (P : MassGap.Transfer.PreForm A) {ι : Type*} (s : Finset ι) (c : ι → ℂ)
    (z : ι → A × A) (w : A × A) :
    cform P w (∑ i ∈ s, cscal (c i) (z i)) = ∑ i ∈ s, c i * cform P w (z i) := by
  classical
  refine Finset.induction_on s ?_ ?_
  · simp only [Finset.sum_empty, cform_zero_right]
  · intro i t hi ih
    rw [Finset.sum_insert hi, Finset.sum_insert hi, cform_add_right, cform_smul_right, ih]

/-- **THE COMPLEX GRAM SUM IS THE FORM AT ONE COMPLEX LINEAR COMBINATION.** -/
theorem cform_gram (P : MassGap.Transfer.PreForm A) {ι : Type*} [Fintype ι] (c : ι → ℂ)
    (z : ι → A × A) :
    cform P (∑ i, cscal (c i) (z i)) (∑ j, cscal (c j) (z j))
      = ∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * cform P (z i) (z j) := by
  rw [cform_sum_left]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [cform_sum_right, Finset.mul_sum]
  exact Finset.sum_congr rfl (fun j _ => (mul_assoc _ _ _).symm)

/-- **THE COMPLEX GRAM MATRIX IS POSITIVE SEMIDEFINITE**, over complex coefficients.

DERIVED: the `0` of `0 ≤ …` is positive semidefiniteness itself. -/
theorem cform_gram_re_nonneg (P : MassGap.Transfer.ReflForm A) {ι : Type*} [Fintype ι] (c : ι → ℂ)
    (z : ι → A × A) :
    0 ≤ (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * cform P.toPreForm (z i) (z j)).re := by
  rw [← cform_gram]
  exact cform_diag_re_nonneg P _

/-- **AND IT IS REAL.** -/
theorem cform_gram_im_zero (P : MassGap.Transfer.PreForm A) {ι : Type*} [Fintype ι] (c : ι → ℂ)
    (z : ι → A × A) :
    (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * cform P (z i) (z j)).im = 0 := by
  rw [← cform_gram]
  exact cform_diag_im_zero P _

end Complexify

/-! ## Part 2 — the Gibbs expectation is additive on the observables in play

`WilsonReal.wilsonSystem_expect_add` carries integrability hypotheses;
`WilsonReal.wilsonSystem_mul_boltz_integrable` discharges them for any bounded measurable observable,
and a member of `localObs` is bounded and measurable by definition. So the two-component
decomposition of the complex pairing can be written as ONE Gibbs expectation rather than as a sum of
two, which is what lets Part 3 state OS3's inequality in OS3's own shape.
-/

section Additivity

variable {d n N : ℕ} [NeZero n]

/-- The reflection form of `Transfer` IS a Gibbs expectation. Definitional, named so the rewrites
below do not have to unfold anything. -/
theorem reflForm_eq_EW (N : ℕ) (τ : Fin d) (rc : Fin n) (β : ℝ)
    (F G : (Link d n → MassGap.SUN.SU N) → ℝ) :
    MassGap.Transfer.reflForm N τ rc β F G
      = EW N β (fun U => F (reflConf τ rc U) * G U) := rfl

/-- The bound on a reflected product, stated at a configuration typed as a link function so that the
two bounds can be applied without unifying `System.Config` with `Link d n → SU N` under a binder.

DERIVED: no numeral; the bound `CF * CG` is read off the product. -/
theorem abs_refl_mul_le (τ : Fin d) (rc : Fin n)
    {F G : (Link d n → MassGap.SUN.SU N) → ℝ} {CF CG : ℝ}
    (hFb : ∀ U, |F U| ≤ CF) (hGb : ∀ U, |G U| ≤ CG) (U : Link d n → MassGap.SUN.SU N) :
    |F (reflConf τ rc U) * G U| ≤ CF * CG := by
  rw [abs_mul]
  exact mul_le_mul (hFb (reflConf τ rc U)) (hGb U) (abs_nonneg _)
    (le_trans (abs_nonneg _) (hFb (reflConf τ rc U)))

/-- **THE EXPECTATION SPLITS OVER A SUM OF TWO REFLECTED PRODUCTS.** Both integrability hypotheses
are discharged from the module's own bound and measurability.

DERIVED: no numeral; the bound `CF * CG` is read off the product, as in `mul_mem_localObs`. -/
theorem EW_add_refl_mul {S R : Finset (Link d n)} (hN : N ≠ 0) (τ : Fin d) (rc : Fin n) (β : ℝ)
    {F₁ G₁ F₂ G₂ : (Link d n → MassGap.SUN.SU N) → ℝ}
    (hF₁ : F₁ ∈ localObs S R) (hG₁ : G₁ ∈ localObs S R)
    (hF₂ : F₂ ∈ localObs S R) (hG₂ : G₂ ∈ localObs S R) :
    EW N β (fun U => F₁ (reflConf τ rc U) * G₁ U + F₂ (reflConf τ rc U) * G₂ U)
      = MassGap.Transfer.reflForm N τ rc β F₁ G₁
        + MassGap.Transfer.reflForm N τ rc β F₂ G₂ := by
  obtain ⟨CF₁, hbF₁⟩ := localObs_bounded hF₁
  obtain ⟨CG₁, hbG₁⟩ := localObs_bounded hG₁
  obtain ⟨CF₂, hbF₂⟩ := localObs_bounded hF₂
  obtain ⟨CG₂, hbG₂⟩ := localObs_bounded hG₂
  have hint : ∀ (F G : (Link d n → MassGap.SUN.SU N) → ℝ) (CF CG : ℝ),
      Measurable F → Measurable G → (∀ U, |F U| ≤ CF) → (∀ U, |G U| ≤ CG) →
      Integrable (fun U => (F (reflConf τ rc U) * G U) * (sysWilson N d n).boltz β U)
        ((sysWilson N d n).vol (probHaar (MassGap.SUN.SU N))) := by
    intro F G CF CG hFm hGm hFb hGb
    exact wilsonSystem_mul_boltz_integrable hN (bd (d := d) (n := n)) β
      (fun U => F (reflConf τ rc U) * G U)
      ((hFm.comp (measurable_reflConf τ rc)).mul hGm) (CF * CG)
      (fun U => abs_refl_mul_le τ rc hFb hGb U)
  exact wilsonSystem_expect_add (bd (d := d) (n := n)) β _ _
    (hint F₁ G₁ CF₁ CG₁ (localObs_measurable hF₁) (localObs_measurable hG₁) hbF₁ hbG₁)
    (hint F₂ G₂ CF₂ CG₂ (localObs_measurable hF₂) (localObs_measurable hG₂) hbF₂ hbG₂)

/-- **NEGATION IN THE UNREFLECTED SLOT**, from unconditional homogeneity of the Gibbs state.

DERIVED: the `-1` is the negation being moved through the expectation, not a chosen scalar. -/
theorem reflForm_neg_right (N : ℕ) (τ : Fin d) (rc : Fin n) (β : ℝ)
    (F G : (Link d n → MassGap.SUN.SU N) → ℝ) :
    MassGap.Transfer.reflForm N τ rc β F (fun U => -(G U))
      = -MassGap.Transfer.reflForm N τ rc β F G := by
  have h1 : MassGap.Transfer.reflForm N τ rc β F (fun U => -(G U))
      = EW N β (fun U => (-1 : ℝ) * (F (reflConf τ rc U) * G U)) :=
    MassGap.Transfer.expect_congr N β (fun U => by
      show F (reflConf τ rc U) * -(G U) = (-1 : ℝ) * (F (reflConf τ rc U) * G U)
      ring)
  have h2 : EW N β (fun U => (-1 : ℝ) * (F (reflConf τ rc U) * G U))
      = (-1 : ℝ) * MassGap.Transfer.reflForm N τ rc β F G :=
    wilsonSystem_expect_smul (bd (d := d) (n := n)) β (-1 : ℝ)
      (fun U => F (reflConf τ rc U) * G U)
  rw [h1, h2]
  ring

end Additivity

/-! ## Part 3 — the complex OS pairing on the Wilson Gibbs state

A complex test observable of the slab is one whose real and imaginary parts are both members of the
slab module. `cform` at the pair of parts is shown to BE the Gibbs expectation of
`conj(F ∘ Θ) · G`, componentwise, so everything Part 1 proved about `cform` is a statement about the
physical complex two-point function.
-/

section ComplexWilson

variable {d n N : ℕ} [NeZero n]

/-- The real part of a complex observable. -/
def reObs (F : (Link d n → MassGap.SUN.SU N) → ℂ) : (Link d n → MassGap.SUN.SU N) → ℝ :=
  fun U => (F U).re

/-- The imaginary part of a complex observable. -/
def imObs (F : (Link d n → MassGap.SUN.SU N) → ℂ) : (Link d n → MassGap.SUN.SU N) → ℝ :=
  fun U => (F U).im

/-- **THE COMPLEX TEST OBSERVABLES OF THE SLAB**: both parts in the slab module. This is the set OS3
quantifies over, restricted to the slab.

DERIVED: no numeral. -/
def localObsC (S R : Finset (Link d n)) : Set ((Link d n → MassGap.SUN.SU N) → ℂ) :=
  {F | reObs F ∈ localObs S R ∧ imObs F ∈ localObs S R}

omit [NeZero n] in
theorem mem_localObsC {S R : Finset (Link d n)}
    {F : (Link d n → MassGap.SUN.SU N) → ℂ} :
    F ∈ localObsC S R ↔ reObs F ∈ localObs S R ∧ imObs F ∈ localObs S R := Iff.rfl

/-- **THE REAL PART OF THE OS INTEGRAND**, pointwise: `Re(conj(F θU) · G U)` pairs like with like. -/
theorem osPairing_re_pointwise (τ : Fin d) (rc : Fin n)
    (F G : (Link d n → MassGap.SUN.SU N) → ℂ) (U : Link d n → MassGap.SUN.SU N) :
    ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).re
      = reObs F (reflConf τ rc U) * reObs G U + imObs F (reflConf τ rc U) * imObs G U := by
  simp only [reObs, imObs, Complex.mul_re, Complex.conj_re, Complex.conj_im]
  ring

/-- **THE IMAGINARY PART OF THE OS INTEGRAND**, pointwise: the antisymmetric cross term. -/
theorem osPairing_im_pointwise (τ : Fin d) (rc : Fin n)
    (F G : (Link d n → MassGap.SUN.SU N) → ℂ) (U : Link d n → MassGap.SUN.SU N) :
    ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).im
      = reObs F (reflConf τ rc U) * imObs G U
        + imObs F (reflConf τ rc U) * (-(reObs G U)) := by
  simp only [reObs, imObs, Complex.mul_im, Complex.conj_re, Complex.conj_im]
  ring

/-- **THE REAL PART OF THE COMPLEX GIBBS PAIRING**, as one expectation of the genuine complex
integrand. -/
theorem wilson_osC_re (hN : N ≠ 0) {S R : Finset (Link d n)} (τ : Fin d) (rc : Fin n) (β : ℝ)
    {F G : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC S R) (hG : G ∈ localObsC S R) :
    EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).re)
      = MassGap.Transfer.reflForm N τ rc β (reObs F) (reObs G)
        + MassGap.Transfer.reflForm N τ rc β (imObs F) (imObs G) := by
  have hcong : EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).re)
      = EW N β (fun U => reObs F (reflConf τ rc U) * reObs G U
          + imObs F (reflConf τ rc U) * imObs G U) :=
    MassGap.Transfer.expect_congr N β (fun U => osPairing_re_pointwise τ rc F G U)
  exact hcong.trans (EW_add_refl_mul hN τ rc β hF.1 hG.1 hF.2 hG.2)

/-- **THE IMAGINARY PART OF THE COMPLEX GIBBS PAIRING**, as one expectation. -/
theorem wilson_osC_im (hN : N ≠ 0) {S R : Finset (Link d n)} (τ : Fin d) (rc : Fin n) (β : ℝ)
    {F G : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC S R) (hG : G ∈ localObsC S R) :
    EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).im)
      = MassGap.Transfer.reflForm N τ rc β (reObs F) (imObs G)
        - MassGap.Transfer.reflForm N τ rc β (imObs F) (reObs G) := by
  have hneg : (fun U => -(reObs G U)) ∈ localObs S R := neg_mem hG.1
  have hcong : EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).im)
      = EW N β (fun U => reObs F (reflConf τ rc U) * imObs G U
          + imObs F (reflConf τ rc U) * (-(reObs G U))) :=
    MassGap.Transfer.expect_congr N β (fun U => osPairing_im_pointwise τ rc F G U)
  rw [hcong, EW_add_refl_mul hN τ rc β hF.1 hG.2 hF.2 hneg,
    reflForm_neg_right N τ rc β (imObs F) (reObs G)]
  ring

end ComplexWilson

/-! ## Part 4 — OS3's positivity clause, complex, on the slab algebra -/

section OS3

variable {d n N : ℕ} [NeZero n]

/-- **THE COMPLEX GIBBS PAIRING IS THE COMPLEXIFIED REFLECTION FORM.**

This is the identification that makes Part 1 a statement about physics rather than about algebra:
`cform` at the pair of parts of `F` and `G` is `⟨conj(F ∘ Θ) · G⟩`, real part and imaginary part.

DERIVED: no numeral. -/
theorem cform_eq_osPairing (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    {F G : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC (blkS τ a m) (blkR τ a m))
    (hG : G ∈ localObsC (blkS τ a m) (blkR τ a m)) :
    cform (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm
        (⟨reObs F, hF.1⟩, ⟨imObs F, hF.2⟩) (⟨reObs G, hG.1⟩, ⟨imObs G, hG.2⟩)
      = ((EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * G U).re) : ℝ) : ℂ)
        + ((EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * G U).im) : ℝ) : ℂ)
          * Complex.I := by
  rw [wilson_osC_re hN τ (a + a) β hF hG, wilson_osC_im hN τ (a + a) β hF hG]
  rfl

/-- **OS3'S POSITIVITY, COMPLEX, ON THE DIAGONAL, AT EVERY REAL COUPLING.**

`0 ≤ ⟨conj(F ∘ Θ) · F⟩` for every complex observable of the slab whose two real components lie in
`LogConvex.localObs (blkS τ a m) (blkR τ a m)`, at the site reflection `Θ = reflConf τ (a + a)`, with
NO sign condition on `β`. One Gibbs expectation of the genuine complex integrand.

DERIVED: the `0` of `0 ≤ …` is positive semidefiniteness itself; the `2` in `n = 2 * m` is the
reflection geometry's. -/
theorem wilson_osC_diag_re_nonneg (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    {F : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC (blkS τ a m) (blkR τ a m)) :
    0 ≤ EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * F U).re) := by
  rw [wilson_osC_re hN τ (a + a) β hF hF]
  have h1 : 0 ≤ MassGap.Transfer.reflForm N τ (a + a) β (reObs F) (reObs F) :=
    (wilsonGibbsReflForm hN τ a m hm hm0 β).form_nonneg ⟨reObs F, hF.1⟩
  have h2 : 0 ≤ MassGap.Transfer.reflForm N τ (a + a) β (imObs F) (imObs F) :=
    (wilsonGibbsReflForm hN τ a m hm hm0 β).form_nonneg ⟨imObs F, hF.2⟩
  linarith

/-- **AND THE DIAGONAL PAIRING IS REAL.** Together with the theorem above this says
`⟨conj(F ∘ Θ) · F⟩` is a nonnegative real number, which is OS3's inequality in full.

DERIVED: the `0` is the vanishing of the imaginary part, not a threshold. -/
theorem wilson_osC_diag_im_zero (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ) (β : ℝ)
    {F : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC (blkS τ a m) (blkR τ a m)) :
    EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * F U).im) = 0 := by
  rw [wilson_osC_im hN τ (a + a) β hF hF,
    MassGap.Transfer.reflForm_symm N τ (a + a) β (reObs F) (imObs F)]
  ring

/-- **OS3'S MATRIX INEQUALITY, SESQUILINEAR, AT EVERY REAL COUPLING.**

For every finite family of complex test observables of the slab and every family of COMPLEX
coefficients, `∑ᵢⱼ conj(cᵢ)·cⱼ·⟨conj(Fᵢ ∘ Θ)·Fⱼ⟩` is a nonnegative real. The pairing entries are the
genuine complex Gibbs pairings by `cform_eq_osPairing`.

DERIVED: the `0` of `0 ≤ …` is positive semidefiniteness itself. -/
theorem wilson_osC_gram_re_nonneg (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) {ι : Type} [Fintype ι] (c : ι → ℂ)
    (z : ι → (↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))
      × ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))) :
    0 ≤ (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j
        * cform (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm (z i) (z j)).re :=
  cform_gram_re_nonneg (wilsonGibbsReflForm hN τ a m hm hm0 β) c z

/-- **AND THE COMPLEX GRAM SUM IS REAL.** -/
theorem wilson_osC_gram_im_zero (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) {ι : Type} [Fintype ι] (c : ι → ℂ)
    (z : ι → (↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))
      × ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))) :
    (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j
        * cform (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm (z i) (z j)).im = 0 :=
  cform_gram_im_zero (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm c z

end OS3

/-! ## Part 5 — the ALGEBRA clause

OS3 is positive semidefiniteness over the positive-time ALGEBRA, not over a subspace. `localObs` is
closed under products and contains the constant (`ReflectionStrong.mul_mem_localObs`,
`one_mem_localObs`); this part extends that to arbitrary finite products and states the Gram
inequality over the monomials in ANY family of generators, which is the algebra generated by them.
-/

section Algebra

variable {ι : Type} {Ω : Type} [MeasurableSpace Ω]

/-- **A FINITE PRODUCT OF OBSERVABLES OF `S ∪ R` IS AN OBSERVABLE OF `S ∪ R`.**

DERIVED: no numeral; the empty product is the constant observable, which is
`one_mem_localObs`'s. -/
theorem prod_mem_localObs {S R : Finset ι} {κ : Type*} (s : Finset κ) (g : κ → (ι → Ω) → ℝ)
    (hg : ∀ k ∈ s, g k ∈ localObs S R) :
    (fun U => ∏ k ∈ s, g k U) ∈ localObs S R := by
  classical
  have hfun : (fun U => ∏ k ∈ s, g k U) = ∏ k ∈ s, g k := by
    funext U
    simp only [Finset.prod_apply]
  rw [hfun]
  exact Finset.prod_induction g (fun F => F ∈ localObs S R)
    (fun x y hx hy => mul_mem_localObs hx hy) one_mem_localObs hg

end Algebra

section AlgebraWilson

variable {d n N : ℕ} [NeZero n]

/-- **THE GRAM MATRIX OVER THE MONOMIALS IN ANY FAMILY OF SLAB OBSERVABLES IS POSITIVE
SEMIDEFINITE, AT EVERY REAL COUPLING.**

This is the combination OS3 asks for and the previous file did not state: `wilson_expect_gram_nonneg`
was positive semidefiniteness over a finite family drawn from the module, and `mul_mem_localObs` was
the algebra structure; here the family ranges over monomials `∏_{k ∈ w i} g k` in arbitrary
generators `g`, so the inequality holds over the unital subalgebra those generators generate rather
than over a subspace of it.

DERIVED: the `0` of `0 ≤ …` is positive semidefiniteness itself; the monomial exponents `w i` are the
caller's. -/
theorem wilson_gram_nonneg_monomials (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) {ι κ : Type} [Fintype ι]
    (g : κ → (Link d n → MassGap.SUN.SU N) → ℝ)
    (hg : ∀ k, g k ∈ localObs (blkS τ a m) (blkR τ a m))
    (w : ι → Finset κ) (c : ι → ℝ) :
    0 ≤ ∑ i, ∑ j, c i * c j
        * EW N β (fun U => (∏ k ∈ w i, g k U)
            * ∏ k ∈ w j, g k (reflConf τ (a + a) U)) :=
  wilson_expect_gram_nonneg hN τ a m hm hm0 β (fun i U => ∏ k ∈ w i, g k U)
    (fun i => prod_mem_localObs (w i) g (fun k _ => hg k)) c

end AlgebraWilson

/-! ## Part 6 — the GNS Hilbert space of the slab algebra

`Transfer.GNS` turns any `ReflForm` into a genuine `InnerProductSpace ℝ`, and
`ReflectionStrong.wilsonGibbsReflForm` is a `ReflForm` on the genuine Wilson Gibbs state with
`form_nonneg` proved. So the Hilbert space OS3 exists to produce is available at finite volume on the
slab algebra, with the Gibbs reflection pairing as its inner product and the constant observable as a
unit vector.
-/

section GNS

variable {d n N : ℕ} [NeZero n]

/-- **THE GNS INNER PRODUCT IS THE GIBBS REFLECTION PAIRING.** -/
theorem slab_inner_mk (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    (F G : ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))) :
    inner ℝ (MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β) F)
        (MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β) G)
      = MassGap.Transfer.reflForm N τ (a + a) β F.1 G.1 :=
  MassGap.Transfer.GNS.inner_mk F G

/-- **THE VACUUM IS A UNIT VECTOR OF THE GNS SPACE.**

`wilsonGibbsReflForm_vac_norm` gives `⟨1,1⟩ = 1`; the GNS norm is the square root of the form, so the
class of the constant observable has norm exactly one.

DERIVED: the `1`s are the constant observable and the total mass of a probability measure, both
`Transfer.reflForm_one_one`'s. -/
theorem slab_vac_norm (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) :
    ‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
        ⟨fun _ => (1 : ℝ), one_mem_localObs⟩‖ = 1 := by
  have h := MassGap.Transfer.GNS.norm_mk_mul_norm_mk
    (P := wilsonGibbsReflForm hN τ a m hm hm0 β)
    (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
      ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))
  rw [wilsonGibbsReflForm_vac_norm hN τ a m hm hm0 β] at h
  have hnn : (0 : ℝ) ≤ ‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
      (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
        ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))‖ := norm_nonneg _
  have hfac : (‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
      (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
        ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))‖ - 1)
      * (‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
          (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
            ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))‖ + 1) = 0 := by
    linear_combination h
  rcases mul_eq_zero.mp hfac with hz | hz
  · linarith
  · linarith

end GNS

/-! ## Part 7 — the time translation, and the two premises it is missing

`WilsonTransfer` proved, on the genuine Wilson measure and at every real coupling:
`shiftObs τ` is a linear endomorphism of the FULL observable space and an algebra map;
`expect_shift_invariant` says the Gibbs expectation is invariant under one lattice step;
`reflForm_shiftObs_symm` says `⟨T F, G⟩ = ⟨F, T G⟩` for the very form
`ReflectionStrong.wilsonGibbsReflForm` carries; and `shiftObs_one` is `T_vac`.

So "no time translation" is no longer the separation it was. What is missing is not the shift but its
compatibility with the SLAB: `Transfer.TransferData.T` must be an endomorphism of the module the form
is positive on, and `WilsonTransfer.shift_not_stable_on_slab` exhibits a link that leaves the slab
under one step. The two `Prop`s below name exactly what is missing, and
`wilsonSlabTransfer` shows nothing else is.
-/

section TimeTranslation

/-- **THE MISSING PREMISE: the slab algebra is stable under one lattice step.**

This is `ReflectionStrong`'s separation 2 — a slab is not a half-space — in the only form that a
transfer operator cares about. `WilsonTransfer.shift_not_stable_on_slab` refutes the corresponding
statement about the support block, and `HalfLineTransfer.const_of_shift_stable` proves that any
submodule of the slab algebra satisfying this premise consists of constant observables at `2 ≤ m`. It
is named as a premise, not offered as a plausible one.

DERIVED: no numeral. -/
def SlabShiftStable (N : ℕ) {d n : ℕ} [NeZero n] (τ : Fin d) (a : Fin n) (m : ℕ) : Prop :=
  ∀ F ∈ localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m),
    MassGap.WilsonTransfer.shiftObs τ F ∈ localObs (blkS τ a m) (blkR τ a m)

/-- **THE SECOND MISSING PREMISE: the shift does not expand the reflection form.**

`Transfer.TransferData.T_contract`. Contractivity is not a consequence of positivity and
self-adjointness together, so it is carried separately, exactly as `Transfer`'s own header says.

DERIVED: no numeral. -/
def SlabShiftContractive (N : ℕ) {d n : ℕ} [NeZero n] (τ : Fin d) (a : Fin n) (m : ℕ)
    (β : ℝ) : Prop :=
  ∀ F ∈ localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m),
    MassGap.Transfer.reflForm N τ (a + a) β
        (MassGap.WilsonTransfer.shiftObs τ F) (MassGap.WilsonTransfer.shiftObs τ F)
      ≤ MassGap.Transfer.reflForm N τ (a + a) β F F

/-- **THE SHIFT, RESTRICTED TO THE SLAB ALGEBRA**, on the stability premise. Linearity is
`shiftObs`'s own. -/
noncomputable def shiftSlab {N d n : ℕ} [NeZero n] (τ : Fin d) (a : Fin n) (m : ℕ)
    (h : SlabShiftStable N τ a m) :
    ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))
      →ₗ[ℝ] ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)) where
  toFun F := ⟨MassGap.WilsonTransfer.shiftObs τ F.1, h F.1 F.2⟩
  map_add' _ _ := Subtype.ext rfl
  map_smul' _ _ := Subtype.ext rfl

/-- **A FULL `Transfer.TransferData` ON THE SLAB ALGEBRA, FROM THE TWO PREMISES AND NOTHING ELSE.**

Every other field is a theorem about the genuine Wilson measure at every real coupling:
`form_symm` is `Transfer.reflForm_symm`, bilinearity and `form_nonneg` are
`ReflectionStrong.wilsonGibbsReflForm`'s, `T_symm` is `WilsonTransfer.reflForm_shiftObs_symm`,
`T_vac` is definitional, and `vac_norm` is `ReflectionStrong.wilsonGibbsReflForm_vac_norm`.

So the distance from what is proved to a transfer operator is exactly `SlabShiftStable` and
`SlabShiftContractive`. The first is the slab-versus-half-space geometry; the second is contractivity.

DERIVED: no numeral. -/
noncomputable def wilsonSlabTransfer {d n N : ℕ} [NeZero n] (hN : N ≠ 0) (τ : Fin d) (a : Fin n)
    (m : ℕ) (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    (hstab : SlabShiftStable N τ a m) (hcon : SlabShiftContractive N τ a m β) :
    MassGap.Transfer.TransferData
      ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)) where
  toReflForm := wilsonGibbsReflForm hN τ a m hm hm0 β
  T := shiftSlab τ a m hstab
  vac := ⟨fun _ => (1 : ℝ), one_mem_localObs⟩
  T_symm F G := MassGap.WilsonTransfer.reflForm_shiftObs_symm N τ (a + a) β F.1 G.1
  T_contract F := hcon F.1 F.2
  T_vac := Subtype.ext rfl
  vac_norm := wilsonGibbsReflForm_vac_norm hN τ a m hm hm0 β

end TimeTranslation

section Audit
#print axioms ceq
#print axioms cscal
#print axioms cform
#print axioms cform_re
#print axioms cform_im
#print axioms cform_conj_symm
#print axioms cform_add_left
#print axioms cform_zero_left
#print axioms cform_smul_left
#print axioms cform_add_right
#print axioms cform_zero_right
#print axioms cform_smul_right
#print axioms cform_diag
#print axioms cform_diag_re_nonneg
#print axioms cform_diag_im_zero
#print axioms cform_sum_left
#print axioms cform_sum_right
#print axioms cform_gram
#print axioms cform_gram_re_nonneg
#print axioms cform_gram_im_zero
#print axioms reflForm_eq_EW
#print axioms abs_refl_mul_le
#print axioms EW_add_refl_mul
#print axioms reflForm_neg_right
#print axioms reObs
#print axioms imObs
#print axioms localObsC
#print axioms mem_localObsC
#print axioms osPairing_re_pointwise
#print axioms osPairing_im_pointwise
#print axioms wilson_osC_re
#print axioms wilson_osC_im
#print axioms cform_eq_osPairing
#print axioms wilson_osC_diag_re_nonneg
#print axioms wilson_osC_diag_im_zero
#print axioms wilson_osC_gram_re_nonneg
#print axioms wilson_osC_gram_im_zero
#print axioms prod_mem_localObs
#print axioms wilson_gram_nonneg_monomials
#print axioms slab_inner_mk
#print axioms slab_vac_norm
#print axioms SlabShiftStable
#print axioms SlabShiftContractive
#print axioms shiftSlab
#print axioms wilsonSlabTransfer
end Audit

end MassGap.OSPositivity
