import Mathlib
import MassGap.ReflectionStrong
import MassGap.WilsonTransfer

/-!
# MassGap.OSPositivity — the complexified reflection pairing on the Wilson slab

`ReflectionStrong` proves `0 ≤ ⟨F * (F ∘ Θ)⟩` for every real bounded measurable observable of the
slab, at every real coupling. This file complexifies that pairing, extends it to the algebra
generated by the slab observables, builds the GNS space, and names the two premises a transfer
operator on the slab would need.

Throughout, `Θ = Reflect.reflConf τ (a + a)` is the site reflection, `⟨·⟩` is
`ReflectPositive.EW N β` on the periodic lattice of even extent `n = 2 * m`, and

    𝔄 = LogConvex.localObs (blkS τ a m) (blkR τ a m)

is the module of bounded measurable observables determined by the slab and its two bounding planes.

## Part 0–1 The complexification

`ceq` settles a complex identity from its two real components. `cscal c z` is complex
multiplication read on a pair of real vectors, with no `Module ℂ` instance on `A × A`, and
`cform P z w` is `(P z₁ w₁ + P z₂ w₂) + i (P z₁ w₂ - P z₂ w₁)`. The section proves conjugate
symmetry, additivity and homogeneity in each slot — conjugate-linear in the reflected slot
(`cform_smul_left`), linear in the other (`cform_smul_right`) — that the diagonal is real
(`cform_diag`, `cform_diag_im_zero`) and nonnegative (`cform_diag_re_nonneg`), and that the complex
Gram sum over any finite family is a nonnegative real (`cform_gram`, `cform_gram_re_nonneg`,
`cform_gram_im_zero`). Only the two nonnegativity results use `form_nonneg`; the rest need symmetry
and bilinearity alone, and `A` is any real module.

## Part 2–3 Identification with the Gibbs pairing

`reflForm_eq_EW` records that `Transfer.reflForm` is a Gibbs expectation by definition.
`EW_add_refl_mul` splits the expectation over a sum of two reflected products, discharging the
integrability hypotheses of `WilsonReal.wilsonSystem_expect_add` from the module's own bound and
measurability. `localObsC S R` is the set of complex observables whose real and imaginary parts lie
in `localObs S R`; `osPairing_re_pointwise` and `osPairing_im_pointwise` expand the integrand
`conj (F ∘ Θ) * G` pointwise, and `wilson_osC_re`, `wilson_osC_im` and `cform_eq_osPairing` show
`cform` at the pair of parts IS that expectation, component by component.

## Part 4 The positivity statements at the Wilson state

`wilson_osC_diag_re_nonneg` and `wilson_osC_diag_im_zero`: `⟨conj (F ∘ Θ) * F⟩` is a nonnegative
real for every `F ∈ localObsC (blkS τ a m) (blkR τ a m)`, at every real `β`.
`wilson_osC_gram_re_nonneg` and `wilson_osC_gram_im_zero` are the matrix form over complex
coefficients.

## Part 5–7 The algebra, the GNS space, and the shift

`prod_mem_localObs` closes `localObs` under arbitrary finite products, and
`wilson_gram_nonneg_monomials` states the Gram inequality over monomials in any family of
generators. `slab_inner_mk` identifies the `Transfer.GNS` inner product with the Gibbs reflection
pairing and `slab_vac_norm` gives the constant observable norm one. `SlabShiftStable` and
`SlabShiftContractive` are the two premises; `shiftSlab` restricts `WilsonTransfer.shiftObs` to the
slab on the first, and `wilsonSlabTransfer` assembles a `Transfer.TransferData` from the two, every
other field being a theorem already available.

## Scope

* Every statement is at a fixed even extent `n = 2 * m` and a fixed spacing, on the periodic
  `sysWilson` measure. No infinite-volume or continuum measure appears in the import closure —
  `InfiniteVolume` takes subsequential limits of finite-volume numbers — so nothing here is
  quantified over one. Universal quantification over `τ`, `a`, `m` and `β` is uniformity in the
  extent, not a limit.
* `blkS τ a m` is a slab, bounded above by the second reflection plane as well as below by the
  first; a periodic lattice has no half-space. `WilsonTransfer.shift_not_stable_on_slab` exhibits a
  link that leaves the support block under one step, and
  `HalfLineTransfer.const_of_shift_stable` (not imported here) shows every shift-stable submodule of
  the slab algebra consists of constant observables at `2 ≤ m`.
* Regularity, Euclidean invariance and ergodicity are not addressed. What Part 7 adds is one
  translation symmetry of the Gibbs state (`WilsonTransfer.expect_shift_invariant`), a lattice
  symmetry.
* Everything runs on the site reflection `reflConf τ (a + a)`. The link reflections are
  `OddLagSplit`'s, use a different decomposition and require `0 ≤ β`; no statement here touches them
  and no statement here carries a sign condition on the coupling.

Foundational footprint only (`#print axioms` at the end).
Build: `python research/code/lean_build.py build MassGap.OSPositivity`.
-/

namespace MassGap.OSPositivity

open MeasureTheory
open MassGap MassGap.Reflect MassGap.WilsonHypercubic MassGap.ReflectionPositivity
open MassGap.WilsonLattice MassGap.CompactGauge MassGap.WilsonReal MassGap.WilsonAction
open MassGap.ActionSplit MassGap.ReflectPositive MassGap.WilsonBridge MassGap.LogConvex
open MassGap.ReflectionStrong

/-! ## Part 0 — complex extensionality, from `Complex.re_add_im`

Every `ℂ`-valued identity below is settled by its two real components. `ceq` is the only place the
passage from components to the complex number itself is made.
-/

/-- `x = y` for complex `x`, `y` with `x.re = y.re` and `x.im = y.im`. Both sides are rewritten by
`Complex.re_add_im` and the two component equalities substituted.

DERIVED: no numeral appears in the statement. -/
theorem ceq {x y : ℂ} (hre : x.re = y.re) (him : x.im = y.im) : x = y := by
  rw [← Complex.re_add_im x, ← Complex.re_add_im y, hre, him]

/-! ## Part 1 — the complexification of a real reflection form

`Transfer.ReflForm` is real and bilinear. A complex test observable is represented as a pair of real
ones, the scalar action is complex multiplication read on that pair, and the form is

    ⟨z, w⟩_ℂ = (⟨z₁, w₁⟩ + ⟨z₂, w₂⟩) + i (⟨z₁, w₂⟩ - ⟨z₂, w₁⟩).

`A` is any real module here. Symmetry and bilinearity carry the algebraic clauses; `form_nonneg` is
used only by `cform_diag_re_nonneg` and `cform_gram_re_nonneg`. Part 3 identifies this form with the
Gibbs pairing of `conj (F ∘ Θ) * G`.
-/

section Complexify

variable {A : Type*} [AddCommGroup A] [Module ℝ A]

/-- `cscal c z = (c.re • z.1 + (-c.im) • z.2, c.re • z.2 + c.im • z.1)`: complex multiplication by
`c` read on a pair of real vectors. No `Module ℂ` instance is placed on `A × A`; the action is this
function, and the homogeneity clauses `cform_smul_left` and `cform_smul_right` are stated through it.

DERIVED: no numeral appears in the statement; `c.re` and `c.im` are the caller's scalar's
components, and `.1`, `.2` are projections. -/
def cscal (c : ℂ) (z : A × A) : A × A :=
  (c.re • z.1 + (-c.im) • z.2, c.re • z.2 + c.im • z.1)

@[simp] theorem cscal_fst (c : ℂ) (z : A × A) :
    (cscal c z).1 = c.re • z.1 + (-c.im) • z.2 := rfl

@[simp] theorem cscal_snd (c : ℂ) (z : A × A) :
    (cscal c z).2 = c.re • z.2 + c.im • z.1 := rfl

/-- `cform P z w = (P.form z.1 w.1 + P.form z.2 w.2) + (P.form z.1 w.2 - P.form z.2 w.1) * I`: the
complexification of a real `Transfer.PreForm`. The real part pairs like component with like; the
imaginary part is the antisymmetric cross term, which is what makes the result conjugate-symmetric
(`cform_conj_symm`) rather than symmetric.

DERIVED: no numeral appears in the statement; `.1` and `.2` are projections and `Complex.I` is a
constant, not a numeral. -/
noncomputable def cform (P : MassGap.Transfer.PreForm A) (z w : A × A) : ℂ :=
  ((P.form z.1 w.1 + P.form z.2 w.2 : ℝ) : ℂ)
    + ((P.form z.1 w.2 - P.form z.2 w.1 : ℝ) : ℂ) * Complex.I

@[simp] theorem cform_re (P : MassGap.Transfer.PreForm A) (z w : A × A) :
    (cform P z w).re = P.form z.1 w.1 + P.form z.2 w.2 := by
  simp [cform]

@[simp] theorem cform_im (P : MassGap.Transfer.PreForm A) (z w : A × A) :
    (cform P z w).im = P.form z.1 w.2 - P.form z.2 w.1 := by
  simp [cform]

/-- `cform P z w = conj (cform P w z)`. Componentwise: the real parts agree by `P.form_symm` on each
diagonal term, and the imaginary parts differ by sign because the cross term is antisymmetric.

DERIVED: no numeral appears in the statement. -/
theorem cform_conj_symm (P : MassGap.Transfer.PreForm A) (z w : A × A) :
    cform P z w = (starRingEnd ℂ) (cform P w z) := by
  refine ceq ?_ ?_
  · simp only [cform_re, Complex.conj_re]
    rw [P.form_symm w.1 z.1, P.form_symm w.2 z.2]
  · simp only [cform_im, Complex.conj_im]
    rw [P.form_symm w.1 z.2, P.form_symm w.2 z.1]
    ring

/-- `cform P (z + z') w = cform P z w + cform P z' w`: additivity in the first (reflected) slot, from
`P.form_add_left` on each of the four real terms.

DERIVED: no numeral appears in the statement. -/
theorem cform_add_left (P : MassGap.Transfer.PreForm A) (z z' w : A × A) :
    cform P (z + z') w = cform P z w + cform P z' w := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.add_re, Complex.add_im, Prod.fst_add, Prod.snd_add,
      P.form_add_left] <;> ring

/-- `cform P 0 w = 0`: the form vanishes when the first slot does, from `P.form_zero_left`.

DERIVED: `0` occurs twice — the zero pair in the first slot, and the complex zero it produces. -/
theorem cform_zero_left (P : MassGap.Transfer.PreForm A) (w : A × A) :
    cform P 0 w = 0 := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.zero_re, Complex.zero_im, Prod.fst_zero, Prod.snd_zero,
      P.form_zero_left] <;> ring

/-- `cform P (cscal c z) w = conj c * cform P z w`: the first slot is conjugate-linear. Expanding
`cscal` and the complex product and applying `P.form_add_left` and `P.form_smul_left` reduces both
components to real identities closed by `ring`.

This clause is what makes the form sesquilinear rather than bilinear.

DERIVED: no numeral appears in the statement. -/
theorem cform_smul_left (P : MassGap.Transfer.PreForm A) (c : ℂ) (z w : A × A) :
    cform P (cscal c z) w = (starRingEnd ℂ) c * cform P z w := by
  refine ceq ?_ ?_ <;>
    simp only [cscal_fst, cscal_snd, cform_re, cform_im, Complex.mul_re, Complex.mul_im,
      Complex.conj_re, Complex.conj_im, P.form_add_left, P.form_smul_left] <;> ring

/-- `cform P z (w + w') = cform P z w + cform P z w'`: additivity in the second slot, from
`P.form_add_right` on each of the four real terms.

DERIVED: no numeral appears in the statement. -/
theorem cform_add_right (P : MassGap.Transfer.PreForm A) (z w w' : A × A) :
    cform P z (w + w') = cform P z w + cform P z w' := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.add_re, Complex.add_im, Prod.fst_add, Prod.snd_add,
      P.form_add_right] <;> ring

/-- `cform P w 0 = 0`: the form vanishes when the second slot does, from `P.form_zero_right`.

DERIVED: `0` occurs twice — the zero pair in the second slot, and the complex zero it produces. -/
theorem cform_zero_right (P : MassGap.Transfer.PreForm A) (w : A × A) :
    cform P w 0 = 0 := by
  refine ceq ?_ ?_ <;>
    simp only [cform_re, cform_im, Complex.zero_re, Complex.zero_im, Prod.fst_zero, Prod.snd_zero,
      P.form_zero_right] <;> ring

/-- `cform P z (cscal c w) = c * cform P z w`: the second slot is linear, with no conjugation, from
`P.form_add_right` and `P.form_smul_right`.

DERIVED: no numeral appears in the statement. -/
theorem cform_smul_right (P : MassGap.Transfer.PreForm A) (c : ℂ) (z w : A × A) :
    cform P z (cscal c w) = c * cform P z w := by
  refine ceq ?_ ?_ <;>
    simp only [cscal_fst, cscal_snd, cform_re, cform_im, Complex.mul_re, Complex.mul_im,
      P.form_add_right, P.form_smul_right] <;> ring

/-- `cform P z z = ((P.form z.1 z.1 + P.form z.2 z.2 : ℝ) : ℂ)`: on the diagonal the value is the
coercion of a real. The imaginary part is `P.form z.1 z.2 - P.form z.2 z.1`, which vanishes by
`P.form_symm`.

DERIVED: no numeral appears in the statement; `.1` and `.2` are projections. -/
theorem cform_diag (P : MassGap.Transfer.PreForm A) (z : A × A) :
    cform P z z = ((P.form z.1 z.1 + P.form z.2 z.2 : ℝ) : ℂ) := by
  refine ceq (by simp) ?_
  simp only [cform_im, Complex.ofReal_im]
  rw [P.form_symm z.1 z.2]
  ring

/-- `0 ≤ (cform P.toPreForm z z).re` for a `Transfer.ReflForm P`. The real part is
`P.form z.1 z.1 + P.form z.2 z.2`, and `P.form_nonneg` bounds each summand.

Scope: this is the first of the two statements in Part 1 that uses `form_nonneg`; the algebraic
clauses need only symmetry and bilinearity.

DERIVED: `0` is the lower bound, which is the positive-semidefiniteness assertion itself. -/
theorem cform_diag_re_nonneg (P : MassGap.Transfer.ReflForm A) (z : A × A) :
    0 ≤ (cform P.toPreForm z z).re := by
  simp only [cform_re]
  exact add_nonneg (P.form_nonneg z.1) (P.form_nonneg z.2)

/-- `(cform P z z).im = 0`, immediate from `cform_diag`, which exhibits the diagonal value as the
coercion of a real.

DERIVED: `0` is the value of the imaginary part. -/
theorem cform_diag_im_zero (P : MassGap.Transfer.PreForm A) (z : A × A) :
    (cform P z z).im = 0 := by
  rw [cform_diag]
  simp

/-- `cform P (∑ i ∈ s, cscal (c i) (z i)) w = ∑ i ∈ s, conj (c i) * cform P (z i) w`: a finite
complex linear combination in the first slot comes out with its coefficients conjugated. Induction
on the `Finset`, with `cform_add_left` and `cform_smul_left` at each step.

DERIVED: no numeral appears in the statement. -/
theorem cform_sum_left (P : MassGap.Transfer.PreForm A) {ι : Type*} (s : Finset ι) (c : ι → ℂ)
    (z : ι → A × A) (w : A × A) :
    cform P (∑ i ∈ s, cscal (c i) (z i)) w
      = ∑ i ∈ s, (starRingEnd ℂ) (c i) * cform P (z i) w := by
  classical
  refine Finset.induction_on s ?_ ?_
  · simp only [Finset.sum_empty, cform_zero_left]
  · intro i t hi ih
    rw [Finset.sum_insert hi, Finset.sum_insert hi, cform_add_left, cform_smul_left, ih]

/-- `cform P w (∑ i ∈ s, cscal (c i) (z i)) = ∑ i ∈ s, c i * cform P w (z i)`: a finite complex
linear combination in the second slot comes out unconjugated. Induction on the `Finset`, with
`cform_add_right` and `cform_smul_right`.

DERIVED: no numeral appears in the statement. -/
theorem cform_sum_right (P : MassGap.Transfer.PreForm A) {ι : Type*} (s : Finset ι) (c : ι → ℂ)
    (z : ι → A × A) (w : A × A) :
    cform P w (∑ i ∈ s, cscal (c i) (z i)) = ∑ i ∈ s, c i * cform P w (z i) := by
  classical
  refine Finset.induction_on s ?_ ?_
  · simp only [Finset.sum_empty, cform_zero_right]
  · intro i t hi ih
    rw [Finset.sum_insert hi, Finset.sum_insert hi, cform_add_right, cform_smul_right, ih]

/-- `cform P (∑ i, cscal (c i) (z i)) (∑ j, cscal (c j) (z j)) = ∑ i, ∑ j, conj (c i) * c j * cform P (z i) (z j)`:
the double sum is the form evaluated at a single complex linear combination on both sides. It is
`cform_sum_left` followed by `cform_sum_right` inside each term.

DERIVED: no numeral appears in the statement. -/
theorem cform_gram (P : MassGap.Transfer.PreForm A) {ι : Type*} [Fintype ι] (c : ι → ℂ)
    (z : ι → A × A) :
    cform P (∑ i, cscal (c i) (z i)) (∑ j, cscal (c j) (z j))
      = ∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * cform P (z i) (z j) := by
  rw [cform_sum_left]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [cform_sum_right, Finset.mul_sum]
  exact Finset.sum_congr rfl (fun j _ => (mul_assoc _ _ _).symm)

/-- `0 ≤ (∑ i, ∑ j, conj (c i) * c j * cform P.toPreForm (z i) (z j)).re` for a `ReflForm P`, any
finite index type and any complex coefficients. `cform_gram` rewrites the double sum as a diagonal
value and `cform_diag_re_nonneg` bounds it.

DERIVED: `0` is the lower bound, which is the positive-semidefiniteness assertion itself. -/
theorem cform_gram_re_nonneg (P : MassGap.Transfer.ReflForm A) {ι : Type*} [Fintype ι] (c : ι → ℂ)
    (z : ι → A × A) :
    0 ≤ (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * cform P.toPreForm (z i) (z j)).re := by
  rw [← cform_gram]
  exact cform_diag_re_nonneg P _

/-- `(∑ i, ∑ j, conj (c i) * c j * cform P (z i) (z j)).im = 0`: the complex Gram sum has no
imaginary part. `cform_gram` rewrites it as a diagonal value and `cform_diag_im_zero` applies.

DERIVED: `0` is the value of the imaginary part. -/
theorem cform_gram_im_zero (P : MassGap.Transfer.PreForm A) {ι : Type*} [Fintype ι] (c : ι → ℂ)
    (z : ι → A × A) :
    (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * cform P (z i) (z j)).im = 0 := by
  rw [← cform_gram]
  exact cform_diag_im_zero P _

end Complexify

/-! ## Part 2 — additivity of the Gibbs expectation on the observables in play

`WilsonReal.wilsonSystem_expect_add` carries integrability hypotheses, and
`WilsonReal.wilsonSystem_mul_boltz_integrable` discharges them for any bounded measurable
observable; a member of `localObs` is bounded and measurable by definition. So the two-component
decomposition of the complex pairing can be written as one Gibbs expectation rather than as a sum of
two.
-/

section Additivity

variable {d n N : ℕ} [NeZero n]

/-- `Transfer.reflForm N τ rc β F G = EW N β (fun U => F (reflConf τ rc U) * G U)`, by `rfl`. Named
so the rewrites below need not unfold the definition.

DERIVED: no numeral appears in the statement. -/
theorem reflForm_eq_EW (N : ℕ) (τ : Fin d) (rc : Fin n) (β : ℝ)
    (F G : (Link d n → MassGap.SUN.SU N) → ℝ) :
    MassGap.Transfer.reflForm N τ rc β F G
      = EW N β (fun U => F (reflConf τ rc U) * G U) := rfl

/-- `|F (reflConf τ rc U) * G U| ≤ CF * CG` from sup-norm bounds `CF` on `F` and `CG` on `G`. Stated
with the configuration typed as a link function so that the two bounds apply without unifying
`System.Config` with `Link d n → SU N` under a binder.

DERIVED: no numeral appears in the statement; the bound `CF * CG` is the product of the caller's two
bounds. -/
theorem abs_refl_mul_le (τ : Fin d) (rc : Fin n)
    {F G : (Link d n → MassGap.SUN.SU N) → ℝ} {CF CG : ℝ}
    (hFb : ∀ U, |F U| ≤ CF) (hGb : ∀ U, |G U| ≤ CG) (U : Link d n → MassGap.SUN.SU N) :
    |F (reflConf τ rc U) * G U| ≤ CF * CG := by
  rw [abs_mul]
  exact mul_le_mul (hFb (reflConf τ rc U)) (hGb U) (abs_nonneg _)
    (le_trans (abs_nonneg _) (hFb (reflConf τ rc U)))

/-- For four observables of `localObs S R`,
`EW N β (F₁ ∘ Θ * G₁ + F₂ ∘ Θ * G₂) = reflForm N τ rc β F₁ G₁ + reflForm N τ rc β F₂ G₂`. It is
`WilsonReal.wilsonSystem_expect_add`, whose two integrability hypotheses are discharged by
`wilsonSystem_mul_boltz_integrable` from `localObs_bounded`, `localObs_measurable` and
`abs_refl_mul_le`.

Scope: `hN : N ≠ 0` is what makes the Gibbs measure well defined; `β` is unconstrained in sign.

DERIVED: `0` is the value `N` is assumed to differ from. -/
theorem EW_add_refl_mul {S R : Finset (Link d n)} (hN : N ≠ 0) (τ : Fin d) (rc : Fin n) (β : ℝ)
    {F₁ G₁ F₂ G₂ : (Link d n → MassGap.SUN.SU N) → ℝ}
    (hF₁ : F₁ ∈ localObs S R) (hG₁ : G₁ ∈ localObs S R)
    (hF₂ : F₂ ∈ localObs S R) (hG₂ : G₂ ∈ localObs S R) :
    EW N β (fun U => F₁ (reflConf τ rc U) * G₁ U + F₂ (reflConf τ rc U) * G₂ U)
      = MassGap.Transfer.reflForm N τ rc β F₁ G₁
        + MassGap.Transfer.reflForm N τ rc β F₂ G₂ := by
  obtain ⟨CF₁, hbF₁⟩ := localObs_bounded hF₁
  obtain ⟨CG₁, hbG₁⟩ := localObs_bounded hG₁
  obtain ⟨CF₂, hbF₂⟩ := localObs_bounded hF₂
  obtain ⟨CG₂, hbG₂⟩ := localObs_bounded hG₂
  have hint : ∀ (F G : (Link d n → MassGap.SUN.SU N) → ℝ) (CF CG : ℝ),
      Measurable F → Measurable G → (∀ U, |F U| ≤ CF) → (∀ U, |G U| ≤ CG) →
      Integrable (fun U => (F (reflConf τ rc U) * G U) * (sysWilson N d n).boltz β U)
        ((sysWilson N d n).vol (probHaar (MassGap.SUN.SU N))) := by
    intro F G CF CG hFm hGm hFb hGb
    exact wilsonSystem_mul_boltz_integrable hN (bd (d := d) (n := n)) β
      (fun U => F (reflConf τ rc U) * G U)
      ((hFm.comp (measurable_reflConf τ rc)).mul hGm) (CF * CG)
      (fun U => abs_refl_mul_le τ rc hFb hGb U)
  exact wilsonSystem_expect_add (bd (d := d) (n := n)) β _ _
    (hint F₁ G₁ CF₁ CG₁ (localObs_measurable hF₁) (localObs_measurable hG₁) hbF₁ hbG₁)
    (hint F₂ G₂ CF₂ CG₂ (localObs_measurable hF₂) (localObs_measurable hG₂) hbF₂ hbG₂)

/-- `reflForm N τ rc β F (fun U => -(G U)) = -reflForm N τ rc β F G`. The integrand is rewritten as
`(-1 : ℝ)` times the original by `Transfer.expect_congr`, and `wilsonSystem_expect_smul` pulls the
scalar out; no integrability hypothesis is needed.

DERIVED: no numeral appears in the statement. The `-1` used to move the sign through the expectation
lives in the proof. -/
theorem reflForm_neg_right (N : ℕ) (τ : Fin d) (rc : Fin n) (β : ℝ)
    (F G : (Link d n → MassGap.SUN.SU N) → ℝ) :
    MassGap.Transfer.reflForm N τ rc β F (fun U => -(G U))
      = -MassGap.Transfer.reflForm N τ rc β F G := by
  have h1 : MassGap.Transfer.reflForm N τ rc β F (fun U => -(G U))
      = EW N β (fun U => (-1 : ℝ) * (F (reflConf τ rc U) * G U)) :=
    MassGap.Transfer.expect_congr N β (fun U => by
      show F (reflConf τ rc U) * -(G U) = (-1 : ℝ) * (F (reflConf τ rc U) * G U)
      ring)
  have h2 : EW N β (fun U => (-1 : ℝ) * (F (reflConf τ rc U) * G U))
      = (-1 : ℝ) * MassGap.Transfer.reflForm N τ rc β F G :=
    wilsonSystem_expect_smul (bd (d := d) (n := n)) β (-1 : ℝ)
      (fun U => F (reflConf τ rc U) * G U)
  rw [h1, h2]
  ring

end Additivity

/-! ## Part 3 — the complex pairing at the Wilson Gibbs state

A complex test observable of the slab is one whose real and imaginary parts both lie in the slab
module. `cform` at the pair of parts is shown to equal the Gibbs expectation of
`conj (F ∘ Θ) * G`, component by component, so Part 1's results apply to that expectation.
-/

section ComplexWilson

variable {d n N : ℕ} [NeZero n]

/-- `reObs F U = (F U).re`: the real part of a complex-valued observable, as a real-valued one.

DERIVED: no numeral appears in the statement. -/
def reObs (F : (Link d n → MassGap.SUN.SU N) → ℂ) : (Link d n → MassGap.SUN.SU N) → ℝ :=
  fun U => (F U).re

/-- `imObs F U = (F U).im`: the imaginary part of a complex-valued observable, as a real-valued one.

DERIVED: no numeral appears in the statement. -/
def imObs (F : (Link d n → MassGap.SUN.SU N) → ℂ) : (Link d n → MassGap.SUN.SU N) → ℝ :=
  fun U => (F U).im

/-- The set of complex-valued observables whose real and imaginary parts both lie in
`localObs S R`: `{F | reObs F ∈ localObs S R ∧ imObs F ∈ localObs S R}`. Membership is `Iff.rfl` by
`mem_localObsC`.

DERIVED: no numeral appears in the statement. -/
def localObsC (S R : Finset (Link d n)) : Set ((Link d n → MassGap.SUN.SU N) → ℂ) :=
  {F | reObs F ∈ localObs S R ∧ imObs F ∈ localObs S R}

omit [NeZero n] in
theorem mem_localObsC {S R : Finset (Link d n)}
    {F : (Link d n → MassGap.SUN.SU N) → ℂ} :
    F ∈ localObsC S R ↔ reObs F ∈ localObs S R ∧ imObs F ∈ localObs S R := Iff.rfl

/-- `(conj (F (reflConf τ rc U)) * G U).re = reObs F (Θ U) * reObs G U + imObs F (Θ U) * imObs G U`
at every configuration: the real part pairs like component with like. Expanding
`Complex.mul_re` with `Complex.conj_re` and `Complex.conj_im` and closing by `ring`.

DERIVED: no numeral appears in the statement. -/
theorem osPairing_re_pointwise (τ : Fin d) (rc : Fin n)
    (F G : (Link d n → MassGap.SUN.SU N) → ℂ) (U : Link d n → MassGap.SUN.SU N) :
    ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).re
      = reObs F (reflConf τ rc U) * reObs G U + imObs F (reflConf τ rc U) * imObs G U := by
  simp only [reObs, imObs, Complex.mul_re, Complex.conj_re, Complex.conj_im]
  ring

/-- `(conj (F (reflConf τ rc U)) * G U).im = reObs F (Θ U) * imObs G U + imObs F (Θ U) * (-(reObs G U))`
at every configuration: the imaginary part is the antisymmetric cross term. The second summand is
written with an explicit negation so that `EW_add_refl_mul` applies to it directly.

DERIVED: no numeral appears in the statement. -/
theorem osPairing_im_pointwise (τ : Fin d) (rc : Fin n)
    (F G : (Link d n → MassGap.SUN.SU N) → ℂ) (U : Link d n → MassGap.SUN.SU N) :
    ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).im
      = reObs F (reflConf τ rc U) * imObs G U
        + imObs F (reflConf τ rc U) * (-(reObs G U)) := by
  simp only [reObs, imObs, Complex.mul_im, Complex.conj_re, Complex.conj_im]
  ring

/-- For `F`, `G` in `localObsC S R`,
`EW N β (fun U => (conj (F (Θ U)) * G U).re) = reflForm N τ rc β (reObs F) (reObs G) + reflForm N τ rc β (imObs F) (imObs G)`.
`Transfer.expect_congr` rewrites the integrand by `osPairing_re_pointwise` and `EW_add_refl_mul`
splits it.

DERIVED: `0` is the value `N` is assumed to differ from. -/
theorem wilson_osC_re (hN : N ≠ 0) {S R : Finset (Link d n)} (τ : Fin d) (rc : Fin n) (β : ℝ)
    {F G : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC S R) (hG : G ∈ localObsC S R) :
    EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).re)
      = MassGap.Transfer.reflForm N τ rc β (reObs F) (reObs G)
        + MassGap.Transfer.reflForm N τ rc β (imObs F) (imObs G) := by
  have hcong : EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).re)
      = EW N β (fun U => reObs F (reflConf τ rc U) * reObs G U
          + imObs F (reflConf τ rc U) * imObs G U) :=
    MassGap.Transfer.expect_congr N β (fun U => osPairing_re_pointwise τ rc F G U)
  exact hcong.trans (EW_add_refl_mul hN τ rc β hF.1 hG.1 hF.2 hG.2)

/-- For `F`, `G` in `localObsC S R`,
`EW N β (fun U => (conj (F (Θ U)) * G U).im) = reflForm N τ rc β (reObs F) (imObs G) - reflForm N τ rc β (imObs F) (reObs G)`.
The integrand is rewritten by `osPairing_im_pointwise`, split by `EW_add_refl_mul` — the negated
observable is in the module by `neg_mem` — and the sign moved out by `reflForm_neg_right`.

DERIVED: `0` is the value `N` is assumed to differ from. -/
theorem wilson_osC_im (hN : N ≠ 0) {S R : Finset (Link d n)} (τ : Fin d) (rc : Fin n) (β : ℝ)
    {F G : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC S R) (hG : G ∈ localObsC S R) :
    EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).im)
      = MassGap.Transfer.reflForm N τ rc β (reObs F) (imObs G)
        - MassGap.Transfer.reflForm N τ rc β (imObs F) (reObs G) := by
  have hneg : (fun U => -(reObs G U)) ∈ localObs S R := neg_mem hG.1
  have hcong : EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ rc U)) * G U).im)
      = EW N β (fun U => reObs F (reflConf τ rc U) * imObs G U
          + imObs F (reflConf τ rc U) * (-(reObs G U))) :=
    MassGap.Transfer.expect_congr N β (fun U => osPairing_im_pointwise τ rc F G U)
  rw [hcong, EW_add_refl_mul hN τ rc β hF.1 hG.2 hF.2 hneg,
    reflForm_neg_right N τ rc β (imObs F) (reObs G)]
  ring

end ComplexWilson

/-! ## Part 4 — the positivity statements at the Wilson state -/

section OS3

variable {d n N : ℕ} [NeZero n]

/-- `cform (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm` at the pairs of parts of `F` and `G`
equals `EW N β ((conj (F ∘ Θ)) * G).re + EW N β ((conj (F ∘ Θ)) * G).im * I`, with
`Θ = reflConf τ (a + a)`. It is `wilson_osC_re` and `wilson_osC_im` substituted into `cform`'s
definition, which then closes by `rfl`.

So every statement Part 1 proves about `cform` at this form is a statement about that expectation.

DERIVED: `0` occurs twice, as the value `N` is assumed to differ from and as the strict lower bound
on `m`; `2` is the factor in the evenness hypothesis `n = 2 * m`. -/
theorem cform_eq_osPairing (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    {F G : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC (blkS τ a m) (blkR τ a m))
    (hG : G ∈ localObsC (blkS τ a m) (blkR τ a m)) :
    cform (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm
        (⟨reObs F, hF.1⟩, ⟨imObs F, hF.2⟩) (⟨reObs G, hG.1⟩, ⟨imObs G, hG.2⟩)
      = ((EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * G U).re) : ℝ) : ℂ)
        + ((EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * G U).im) : ℝ) : ℂ)
          * Complex.I := by
  rw [wilson_osC_re hN τ (a + a) β hF hG, wilson_osC_im hN τ (a + a) β hF hG]
  rfl

/-- `0 ≤ EW N β (fun U => (conj (F (Θ U)) * F U).re)` for every `F` whose real and imaginary parts
lie in `localObs (blkS τ a m) (blkR τ a m)`, at the site reflection `Θ = reflConf τ (a + a)`, at
every real `β`. `wilson_osC_re` splits it into two real reflection forms and
`wilsonGibbsReflForm`'s `form_nonneg` bounds each.

Scope: no sign condition on `β`. The extent must be even, `n = 2 * m` with `0 < m`, which is the
reflection geometry `wilsonGibbsReflForm` requires.

DERIVED: `0` occurs three times — the value `N` is assumed to differ from, the strict lower bound on
`m`, and the lower bound of the expectation, which is the positivity assertion itself. `2` is the
factor in the evenness hypothesis `n = 2 * m`. -/
theorem wilson_osC_diag_re_nonneg (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    {F : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC (blkS τ a m) (blkR τ a m)) :
    0 ≤ EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * F U).re) := by
  rw [wilson_osC_re hN τ (a + a) β hF hF]
  have h1 : 0 ≤ MassGap.Transfer.reflForm N τ (a + a) β (reObs F) (reObs F) :=
    (wilsonGibbsReflForm hN τ a m hm hm0 β).form_nonneg ⟨reObs F, hF.1⟩
  have h2 : 0 ≤ MassGap.Transfer.reflForm N τ (a + a) β (imObs F) (imObs F) :=
    (wilsonGibbsReflForm hN τ a m hm hm0 β).form_nonneg ⟨imObs F, hF.2⟩
  linarith

/-- `EW N β (fun U => (conj (F (Θ U)) * F U).im) = 0`: the diagonal pairing has no imaginary part.
`wilson_osC_im` writes it as a difference of two reflection forms, and `Transfer.reflForm_symm`
makes them equal.

Scope: unlike `wilson_osC_diag_re_nonneg` this needs no evenness or positivity hypothesis on the
extent — only symmetry of the form. Together the two say the diagonal pairing is a nonnegative real.

DERIVED: `0` occurs twice — the value `N` is assumed to differ from, and the value of the imaginary
part. -/
theorem wilson_osC_diag_im_zero (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ) (β : ℝ)
    {F : (Link d n → MassGap.SUN.SU N) → ℂ}
    (hF : F ∈ localObsC (blkS τ a m) (blkR τ a m)) :
    EW N β (fun U => ((starRingEnd ℂ) (F (reflConf τ (a + a) U)) * F U).im) = 0 := by
  rw [wilson_osC_im hN τ (a + a) β hF hF,
    MassGap.Transfer.reflForm_symm N τ (a + a) β (reObs F) (imObs F)]
  ring

/-- `cform_gram_re_nonneg` at `wilsonGibbsReflForm hN τ a m hm hm0 β`: for every finite family `z` of
pairs of slab observables and every family `c` of complex coefficients,
`0 ≤ (∑ i, ∑ j, conj (c i) * c j * cform … (z i) (z j)).re`, at every real `β`.
`cform_eq_osPairing` identifies each entry with the Gibbs pairing.

DERIVED: `0` occurs three times — the value `N` is assumed to differ from, the strict lower bound on
`m`, and the lower bound of the sum, which is the positivity assertion itself. `2` is the factor in
the evenness hypothesis `n = 2 * m`. -/
theorem wilson_osC_gram_re_nonneg (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) {ι : Type} [Fintype ι] (c : ι → ℂ)
    (z : ι → (↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))
      × ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))) :
    0 ≤ (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j
        * cform (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm (z i) (z j)).re :=
  cform_gram_re_nonneg (wilsonGibbsReflForm hN τ a m hm hm0 β) c z

/-- `cform_gram_im_zero` at `wilsonGibbsReflForm hN τ a m hm hm0 β`: the same double sum has
imaginary part `0`.

DERIVED: `0` occurs three times — the value `N` is assumed to differ from, the strict lower bound on
`m`, and the value of the imaginary part. `2` is the factor in the evenness hypothesis
`n = 2 * m`. -/
theorem wilson_osC_gram_im_zero (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) {ι : Type} [Fintype ι] (c : ι → ℂ)
    (z : ι → (↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))
      × ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))) :
    (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j
        * cform (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm (z i) (z j)).im = 0 :=
  cform_gram_im_zero (wilsonGibbsReflForm hN τ a m hm hm0 β).toPreForm c z

end OS3

/-! ## Part 5 — from a subspace to the algebra it generates

`localObs` is closed under products and contains the constant
(`ReflectionStrong.mul_mem_localObs`, `one_mem_localObs`). This part extends closure to arbitrary
finite products and states the Gram inequality over the monomials in any family of generators, which
ranges over the unital subalgebra those generators generate.
-/

section Algebra

variable {ι : Type} {Ω : Type} [MeasurableSpace Ω]

/-- If `g k ∈ localObs S R` at every `k ∈ s`, then `fun U => ∏ k ∈ s, g k U` is in `localObs S R`.
The pointwise product is rewritten as a product in the function algebra and `Finset.prod_induction`
applied, with `mul_mem_localObs` for the step and `one_mem_localObs` for the empty product.

DERIVED: no numeral appears in the statement; the empty product is the constant observable, which is
`one_mem_localObs`'s. -/
theorem prod_mem_localObs {S R : Finset ι} {κ : Type*} (s : Finset κ) (g : κ → (ι → Ω) → ℝ)
    (hg : ∀ k ∈ s, g k ∈ localObs S R) :
    (fun U => ∏ k ∈ s, g k U) ∈ localObs S R := by
  classical
  have hfun : (fun U => ∏ k ∈ s, g k U) = ∏ k ∈ s, g k := by
    funext U
    simp only [Finset.prod_apply]
  rw [hfun]
  exact Finset.prod_induction g (fun F => F ∈ localObs S R)
    (fun x y hx hy => mul_mem_localObs hx hy) one_mem_localObs hg

end Algebra

section AlgebraWilson

variable {d n N : ℕ} [NeZero n]

/-- For any family of generators `g : κ → …` lying in `localObs (blkS τ a m) (blkR τ a m)`, any
finite family of monomial supports `w : ι → Finset κ` and any real coefficients `c`,
`0 ≤ ∑ i, ∑ j, c i * c j * EW N β ((∏ k ∈ w i, g k) * (∏ k ∈ w j, g k) ∘ Θ)`. It is
`ReflectionStrong.wilson_expect_gram_nonneg` at the family of monomials, whose membership is
`prod_mem_localObs`.

So the inequality ranges over the unital subalgebra the generators generate, not only over a
subspace.

DERIVED: `0` occurs three times — the value `N` is assumed to differ from, the strict lower bound on
`m`, and the lower bound of the sum. `2` is the factor in the evenness hypothesis `n = 2 * m`. The
monomial supports `w i` are the caller's. -/
theorem wilson_gram_nonneg_monomials (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) {ι κ : Type} [Fintype ι]
    (g : κ → (Link d n → MassGap.SUN.SU N) → ℝ)
    (hg : ∀ k, g k ∈ localObs (blkS τ a m) (blkR τ a m))
    (w : ι → Finset κ) (c : ι → ℝ) :
    0 ≤ ∑ i, ∑ j, c i * c j
        * EW N β (fun U => (∏ k ∈ w i, g k U)
            * ∏ k ∈ w j, g k (reflConf τ (a + a) U)) :=
  wilson_expect_gram_nonneg hN τ a m hm hm0 β (fun i U => ∏ k ∈ w i, g k U)
    (fun i => prod_mem_localObs (w i) g (fun k _ => hg k)) c

end AlgebraWilson

/-! ## Part 6 — the GNS space of the slab algebra

`Transfer.GNS` turns any `ReflForm` into an `InnerProductSpace ℝ`, and
`ReflectionStrong.wilsonGibbsReflForm` is a `ReflForm` on the Wilson Gibbs state with `form_nonneg`
proved. The two theorems below identify the inner product with the Gibbs reflection pairing and give
the constant observable norm one.
-/

section GNS

variable {d n N : ℕ} [NeZero n]

/-- `inner ℝ (GNS.mk P F) (GNS.mk P G) = Transfer.reflForm N τ (a + a) β F.1 G.1` for
`P = wilsonGibbsReflForm hN τ a m hm hm0 β`. It is `Transfer.GNS.inner_mk` at that form.

DERIVED: `0` occurs twice, as the value `N` is assumed to differ from and as the strict lower bound
on `m`; `2` is the factor in the evenness hypothesis `n = 2 * m`. -/
theorem slab_inner_mk (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    (F G : ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))) :
    inner ℝ (MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β) F)
        (MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β) G)
      = MassGap.Transfer.reflForm N τ (a + a) β F.1 G.1 :=
  MassGap.Transfer.GNS.inner_mk F G

/-- `‖GNS.mk P ⟨fun _ => 1, one_mem_localObs⟩‖ = 1` for
`P = wilsonGibbsReflForm hN τ a m hm hm0 β`. `Transfer.GNS.norm_mk_mul_norm_mk` gives the norm
squared as the form's diagonal value, which `wilsonGibbsReflForm_vac_norm` evaluates to `1`;
factoring `x ^ 2 - 1` and discarding the negative root gives the norm.

DERIVED: `0` occurs twice, as the value `N` is assumed to differ from and as the strict lower bound
on `m`; `2` is the factor in the evenness hypothesis `n = 2 * m`; `1` occurs twice, as the constant
observable's value and as the norm it is shown to have — the latter being the total mass of a
probability measure, through `Transfer.reflForm_one_one`. -/
theorem slab_vac_norm (hN : N ≠ 0) (τ : Fin d) (a : Fin n) (m : ℕ)
    (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ) :
    ‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
        ⟨fun _ => (1 : ℝ), one_mem_localObs⟩‖ = 1 := by
  have h := MassGap.Transfer.GNS.norm_mk_mul_norm_mk
    (P := wilsonGibbsReflForm hN τ a m hm hm0 β)
    (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
      ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))
  rw [wilsonGibbsReflForm_vac_norm hN τ a m hm hm0 β] at h
  have hnn : (0 : ℝ) ≤ ‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
      (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
        ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))‖ := norm_nonneg _
  have hfac : (‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
      (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
        ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))‖ - 1)
      * (‖MassGap.Transfer.GNS.mk (wilsonGibbsReflForm hN τ a m hm hm0 β)
          (⟨fun _ => (1 : ℝ), one_mem_localObs⟩ :
            ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)))‖ + 1) = 0 := by
    linear_combination h
  rcases mul_eq_zero.mp hfac with hz | hz
  · linarith
  · linarith

end GNS

/-! ## Part 7 — the time translation, and the two premises it needs on the slab

`WilsonTransfer` supplies, on the Wilson measure at every real coupling: `shiftObs τ` as a linear
endomorphism of the full observable space and an algebra map; `expect_shift_invariant`, invariance of
the Gibbs expectation under one lattice step; `reflForm_shiftObs_symm`, `⟨T F, G⟩ = ⟨F, T G⟩` for the
form `ReflectionStrong.wilsonGibbsReflForm` carries; and `shiftObs_one`.

What a `Transfer.TransferData` additionally requires is that `T` be an endomorphism of the module the
form is positive on, and that it not expand the form.
`WilsonTransfer.shift_not_stable_on_slab` exhibits a link that leaves the support block under one
step. The two `Prop`s below name those requirements, and `wilsonSlabTransfer` assembles the
structure from them.
-/

section TimeTranslation

/-- The proposition `∀ F ∈ localObs (blkS τ a m) (blkR τ a m), WilsonTransfer.shiftObs τ F ∈ localObs (blkS τ a m) (blkR τ a m)`:
the slab module is stable under one lattice step.

Scope: a `def ... : Prop`, a hypothesis shape rather than a theorem.
`WilsonTransfer.shift_not_stable_on_slab` refutes the corresponding statement about the support
block, and `HalfLineTransfer.const_of_shift_stable` shows every submodule of the slab algebra
satisfying this consists of constant observables at `2 ≤ m`.

DERIVED: no numeral appears in the statement. -/
def SlabShiftStable (N : ℕ) {d n : ℕ} [NeZero n] (τ : Fin d) (a : Fin n) (m : ℕ) : Prop :=
  ∀ F ∈ localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m),
    MassGap.WilsonTransfer.shiftObs τ F ∈ localObs (blkS τ a m) (blkR τ a m)

/-- The proposition that the shift does not increase the reflection form on the slab module:
`reflForm N τ (a + a) β (shiftObs τ F) (shiftObs τ F) ≤ reflForm N τ (a + a) β F F` for every
`F ∈ localObs (blkS τ a m) (blkR τ a m)`. It is the `T_contract` field of
`Transfer.TransferData`, carried separately because contractivity does not follow from positivity
and symmetry.

DERIVED: no numeral appears in the statement. -/
def SlabShiftContractive (N : ℕ) {d n : ℕ} [NeZero n] (τ : Fin d) (a : Fin n) (m : ℕ)
    (β : ℝ) : Prop :=
  ∀ F ∈ localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m),
    MassGap.Transfer.reflForm N τ (a + a) β
        (MassGap.WilsonTransfer.shiftObs τ F) (MassGap.WilsonTransfer.shiftObs τ F)
      ≤ MassGap.Transfer.reflForm N τ (a + a) β F F

/-- `WilsonTransfer.shiftObs τ` restricted to `localObs (blkS τ a m) (blkR τ a m)`, as an `ℝ`-linear
endomorphism, given `SlabShiftStable N τ a m` to place the image back in the module. Additivity and
homogeneity are `Subtype.ext rfl`, since they hold for `shiftObs` itself.

DERIVED: no numeral appears in the statement. -/
noncomputable def shiftSlab {N d n : ℕ} [NeZero n] (τ : Fin d) (a : Fin n) (m : ℕ)
    (h : SlabShiftStable N τ a m) :
    ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m))
      →ₗ[ℝ] ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)) where
  toFun F := ⟨MassGap.WilsonTransfer.shiftObs τ F.1, h F.1 F.2⟩
  map_add' _ _ := Subtype.ext rfl
  map_smul' _ _ := Subtype.ext rfl

/-- A `Transfer.TransferData` on `localObs (blkS τ a m) (blkR τ a m)`, built from
`SlabShiftStable N τ a m` and `SlabShiftContractive N τ a m β`.

The remaining fields come from results already available at every real coupling: `toReflForm` is
`ReflectionStrong.wilsonGibbsReflForm`, which carries symmetry, bilinearity and `form_nonneg`; `T` is
`shiftSlab`; `vac` is the constant observable; `T_symm` is
`WilsonTransfer.reflForm_shiftObs_symm`; `T_contract` is the second premise; `T_vac` is
`Subtype.ext rfl`; and `vac_norm` is `wilsonGibbsReflForm_vac_norm`.

Scope: the two premises are the only hypotheses beyond `N ≠ 0` and the even-extent geometry. Neither
is established here.

DERIVED: `0` occurs twice, as the value `N` is assumed to differ from and as the strict lower bound
on `m`; `2` is the factor in the evenness hypothesis `n = 2 * m`. The `1` in the `vac` field is the
constant observable's value and appears in the body, not the statement. -/
noncomputable def wilsonSlabTransfer {d n N : ℕ} [NeZero n] (hN : N ≠ 0) (τ : Fin d) (a : Fin n)
    (m : ℕ) (hm : n = 2 * m) (hm0 : 0 < m) (β : ℝ)
    (hstab : SlabShiftStable N τ a m) (hcon : SlabShiftContractive N τ a m β) :
    MassGap.Transfer.TransferData
      ↥(localObs (Ω := MassGap.SUN.SU N) (blkS τ a m) (blkR τ a m)) where
  toReflForm := wilsonGibbsReflForm hN τ a m hm hm0 β
  T := shiftSlab τ a m hstab
  vac := ⟨fun _ => (1 : ℝ), one_mem_localObs⟩
  T_symm F G := MassGap.WilsonTransfer.reflForm_shiftObs_symm N τ (a + a) β F.1 G.1
  T_contract F := hcon F.1 F.2
  T_vac := Subtype.ext rfl
  vac_norm := wilsonGibbsReflForm_vac_norm hN τ a m hm hm0 β

end TimeTranslation

section Audit
#print axioms ceq
#print axioms cscal
#print axioms cform
#print axioms cform_re
#print axioms cform_im
#print axioms cform_conj_symm
#print axioms cform_add_left
#print axioms cform_zero_left
#print axioms cform_smul_left
#print axioms cform_add_right
#print axioms cform_zero_right
#print axioms cform_smul_right
#print axioms cform_diag
#print axioms cform_diag_re_nonneg
#print axioms cform_diag_im_zero
#print axioms cform_sum_left
#print axioms cform_sum_right
#print axioms cform_gram
#print axioms cform_gram_re_nonneg
#print axioms cform_gram_im_zero
#print axioms reflForm_eq_EW
#print axioms abs_refl_mul_le
#print axioms EW_add_refl_mul
#print axioms reflForm_neg_right
#print axioms reObs
#print axioms imObs
#print axioms localObsC
#print axioms mem_localObsC
#print axioms osPairing_re_pointwise
#print axioms osPairing_im_pointwise
#print axioms wilson_osC_re
#print axioms wilson_osC_im
#print axioms cform_eq_osPairing
#print axioms wilson_osC_diag_re_nonneg
#print axioms wilson_osC_diag_im_zero
#print axioms wilson_osC_gram_re_nonneg
#print axioms wilson_osC_gram_im_zero
#print axioms prod_mem_localObs
#print axioms wilson_gram_nonneg_monomials
#print axioms slab_inner_mk
#print axioms slab_vac_norm
#print axioms SlabShiftStable
#print axioms SlabShiftContractive
#print axioms shiftSlab
#print axioms wilsonSlabTransfer
end Audit

end MassGap.OSPositivity
