import Mathlib
import MassGap.Complete
import MassGap.Spectral2
import MassGap.TailRatio

/-!
# MassGap.SpectralFour — the extent-four representable region, exactly

`Complete.WilsonSpectral N β` is `Nonempty (Spectral.PeriodicSpectralForm (N+1) (wilsonCorrAt N β))`.
At the Clay aperture `N = 3` the period is four, and `PeriodicSpectralForm.hrep` unfolds to three
independent equations in the three numbers `ρ(0), ρ(1), ρ(2)` (lag three repeats lag one, since
`4 − 3 = 1` and `4 − 1 = 3`):

    ρ(0) = ∑ₖ wₖ (1 + λₖ⁴),   ρ(1) = ∑ₖ wₖ (λₖ + λₖ³),   ρ(2) = ∑ₖ wₖ · 2λₖ².

At this extent the object is not a spectral decomposition of an operator but a finite conic
representation of a triple: the condition on `ρ` is that the triple lies in the cone generated by the
curve `λ ↦ (1 + λ⁴, λ + λ³, 2λ²)`.

## The characterisation

`four_iff`: a form exists for `ρ : Fin 4 → ℝ` exactly when `ρ 3 = ρ 1` and

    0 ≤ ρ(0),   0 ≤ ρ(2),   ρ(2) ≤ ρ(1),   2·ρ(1)² ≤ ρ(2)² + ρ(0)·ρ(2).

That is `FourRepresentable`. Necessity is two pointwise facts and one Cauchy–Schwarz; sufficiency is
an explicit two-mode witness, one mode at `λ = 0` carrying the contact term and one at
`λ = c − √(c²−1)` with `c = ρ(1)/ρ(2)`, so two modes suffice and the third free parameter a
three-mode form would offer is never used. `Nonempty` is therefore decided by a semialgebraic
condition on the triple.

Three readings of that region, all machine-checked here:

* **The two-term shape is not a restriction at this extent.** `fourRepresentable_of_pairs` proves
  that every finite transfer-matrix periodic correlator lands in the region:
  `Tr(A Tᵈ A T⁴⁻ᵈ) = ∑ᵢⱼ |Aᵢⱼ|² λᵢᵈ λⱼ⁴⁻ᵈ`, one term `c (aᵈ b⁴⁻ᵈ + bᵈ a⁴⁻ᵈ)` per unordered pair, and
  each such pair lands on the boundary surface `2ρ₁² = ρ₂² + ρ₀ρ₂` — at the ray the one-parameter
  curve reaches at `λ = a/b`. So `FourRepresentable` is what "this triple came from a finite transfer
  matrix" says about three numbers.
* **`λ ≤ 1` is inert at this extent.** `fourRepresentable_of_sums` proves the necessary conditions
  from `0 ≤ w` and `0 ≤ λ` alone, and `nonempty_of_fourRepresentable` produces a witness that does
  satisfy `λ ≤ 1`. So dropping the upper bound enlarges nothing (`unit_bound_inert`). The triple
  depends on `λ` only through `λ + 1/λ`, which is invariant under `λ ↦ 1/λ`. The binding constraints
  are `w ≥ 0` and `λ ≥ 0`.
* **The region is strictly inside log-convexity.** `fourRepresentable_le` derives
  `ρ(2) ≤ ρ(1) ≤ ρ(0)` and `ρ(1)² ≤ ρ(0)·ρ(2)` from `FourRepresentable`, so the representable region
  implies every field of `TailRatio.TripleFacts` except the strictness `0 < ρ(0)` and the uniform
  bound `≤ 4`, neither of which is a shape fact — and the converse fails.

## The shape facts do not cut out the region

`TailRatio.TripleFacts` collects the shape facts about `(ρ0, ρ1, ρ2)` at extent four;
`TailRatio.triple_wilsonCorrAt` proves it of the Wilson triple at every `0 ≤ β`, from
`PlaqVariance.corrClay_zero_pos`, `Complete.wilson_reflection_positive_at_even`,
`ReflectionStrong.corrClay_nonneg_even_lag`, `LogConvex.corrClay_log_convex_at_extent_four` and
`InfiniteVolume.wilsonCorrAt_abs_le_four`. `tripleFacts_not_ordered` and
`tripleFacts_not_quadratic` exhibit conforming triples that are not representable — one violating
`ρ(2) ≤ ρ(1)`, one violating the quadratic — and `missing_inequalities_independent` shows neither of
those two inequalities follows from the other over the conforming triples.

Positive-definiteness on the whole circle does not supply them either.
`circle_psd_not_sufficient` shows both witnesses are positive-definite as functions on `ℤ₄`, which
is strictly more than `TripleFacts` carries, and `ordered_is_what_nonneg_lam_buys` shows `(4, 0, 4)`
satisfies `hrep` at all three independent lags with `w = (1, 1)` and `λ = (1, −1)`, failing
`PeriodicSpectralForm` only on `hlam0 : 0 ≤ lam`. So `ρ(2) ≤ ρ(1)` is the positivity of the transfer
spectrum rather than an estimate on a correlation.

`WilsonFourRepresentable β` names the condition on the Wilson triple.
`wilsonSpectral_of_representable` and `wilsonSpectral_iff` make it equivalent to
`WilsonSpectral 3 β` at the Clay aperture; it holds at every `0 ≤ β` by
`LinkGram.wilson_lag_two_le_lag_one` and `SlabQuadratic.wilson_quadratic`, with
`SlabQuadratic.wilsonSpectral` the composite.

`FourRepresentable` bounds no ratio: it is satisfied by the constant triple `(c, c, c)` at every
`c ≥ 0` (`fourRepresentable_const`), where `ρ(2)/ρ(0) = 1`. Neither of the two inequalities is a
threshold and neither carries a constant.

Build: `python research/code/lean_build.py build MassGap.SpectralFour`.
-/

namespace MassGap.SpectralFour

open MassGap

/-! ## 0. Lag indices at extent four

DERIVED: `0`, `1`, `2`, `3` are the four lag indices of `Fin 4` and `4` is the period, which is
`N + 1` at the Clay aperture `N = 3`. No numeral in this section is a value. -/

private lemma val0 : ((0 : Fin 4) : ℕ) = 0 := rfl
private lemma val1 : ((1 : Fin 4) : ℕ) = 1 := rfl
private lemma val2 : ((2 : Fin 4) : ℕ) = 2 := rfl
private lemma val3 : ((3 : Fin 4) : ℕ) = 3 := rfl

/-! ## 1. The region -/

/-- **The representable region at extent four.** The conjunction `0 ≤ r₀`, `0 ≤ r₂`, `r₂ ≤ r₁`,
`2r₁² ≤ r₂² + r₀r₂` on a triple of reals.

`fourRepresentable_of_form` shows a `Spectral.PeriodicSpectralForm 4` forces it, and
`nonempty_of_fourRepresentable` shows it plus the circle symmetry `ρ 3 = ρ 1` produces one;
`four_iff` is the resulting equivalence. `FourRepresentable` alone does not decide the `Nonempty` —
the symmetry is the other half.

Geometrically it is the convex cone on the curve `λ ↦ (1 + λ⁴, λ + λ³, 2λ²)`. In the normalised
coordinates `x = ρ1/ρ0`, `y = ρ2/ρ0` that curve is the arc `2x² = y² + y` from `(0,0)` to `(1,1)`,
which as a function of `x` is `y = (√(1 + 8x²) − 1)/2`, convex. So the arc lies below the chord
`y = x` and the hull of the two is the region between them — the chord giving `ρ2 ≤ ρ1` and the arc
giving `2ρ1² ≤ ρ2² + ρ0·ρ2`. (Read the other way round, `x` as a function of `y`, the same arc is
concave; it is the region that is convex, and which variable is named matters for the word.)

DERIVED: the two `0`s are signs. The coefficient `2` in `2 * r₁ ^ 2` is the number of terms in
`λ^d + λ^{n−d}` at the self-paired lag `d = 2`, where `4 − 2 = 2`; it is the shape's own
multiplicity, not a level. The three `2`s in exponent position are squares. No magnitude is chosen
and no threshold appears. -/
def FourRepresentable (r₀ r₁ r₂ : ℝ) : Prop :=
  0 ≤ r₀ ∧ 0 ≤ r₂ ∧ r₂ ≤ r₁ ∧ 2 * r₁ ^ 2 ≤ r₂ ^ 2 + r₀ * r₂

/-- **The region is ordered and log-convex.** From `FourRepresentable r₀ r₁ r₂` follow `r₂ ≤ r₁`,
`r₁ ≤ r₀` and `r₁² ≤ r₀·r₂`.

Taken with `TailRatio.TripleFacts`'s own fields, this means representability gives every field of
`TripleFacts` except the strictness at lag zero and the uniform bound `≤ 4`, which are facts about
the Wilson correlation and not about the shape. The converse fails —
`tripleFacts_not_ordered` and `tripleFacts_not_quadratic` exhibit the counterexamples.

DERIVED: the only numeral in the statement is the exponent `2` of the square `r₁ ^ 2`. -/
theorem fourRepresentable_le {r₀ r₁ r₂ : ℝ} (h : FourRepresentable r₀ r₁ r₂) :
    r₂ ≤ r₁ ∧ r₁ ≤ r₀ ∧ r₁ ^ 2 ≤ r₀ * r₂ := by
  obtain ⟨h0, h2, hord, hq⟩ := h
  have h1 : 0 ≤ r₁ := le_trans h2 hord
  have hsq : r₂ ^ 2 ≤ r₀ * r₂ := by nlinarith [sq_nonneg r₂, sq_nonneg (r₁ - r₂)]
  have hlc : r₁ ^ 2 ≤ r₀ * r₂ := by nlinarith
  have hle : r₁ ≤ r₀ := by nlinarith [sq_nonneg (r₁ - r₀), sq_nonneg (r₁ + r₀)]
  exact ⟨hord, hle, hlc⟩

/-- **The constant triple is representable, at every nonnegative level.** `FourRepresentable c c c`
holds whenever `0 ≤ c`, and `ρ(2)/ρ(0) = 1` there, so `FourRepresentable` bounds no ratio of the
triple's entries: it is a shape condition, not a decay condition.

DERIVED: the only numeral is the `0` in `0 ≤ c`, the sign the region's first two conjuncts require.
`c` is a variable, not a level; the statement quantifies over it. -/
theorem fourRepresentable_const {c : ℝ} (hc : 0 ≤ c) : FourRepresentable c c c :=
  ⟨hc, hc, le_rfl, by nlinarith⟩

/-! ## 2. Necessity -/

/-- **The region contains every sum of unordered-pair terms with nonnegative coefficients.** For any
finite index type and any `c, a, b : κ → ℝ` that are pointwise nonnegative, the three sums
`∑ c (a⁴ + b⁴)`, `∑ c (a b³ + b a³)`, `∑ c (a² b² + b² a²)` satisfy `FourRepresentable`.

The motivating case: for `T` diagonalised with nonnegative eigenvalues `λᵢ` and `A` self-adjoint in
that basis,
`Tr(A Tᵈ A T⁴⁻ᵈ) = ∑ᵢⱼ Aᵢⱼ Aⱼᵢ λᵢᵈ λⱼ⁴⁻ᵈ = ∑ᵢⱼ |Aᵢⱼ|² λᵢᵈ λⱼ⁴⁻ᵈ`, and grouping `(i,j)` with `(j,i)`
leaves one term `c (aᵈ b⁴⁻ᵈ + bᵈ a⁴⁻ᵈ)` per unordered pair. The coefficient `c = |Aᵢⱼ|² ≥ 0` is
entrywise nonnegative with no semidefiniteness needed, because it is a squared modulus — and the
self-adjointness of `A` is what turns `Aᵢⱼ Aⱼᵢ` into it. Those two, and diagonalisability of `T` with
`λ ≥ 0`, are assumptions of that calculation; they are not hypotheses of this theorem, which is about
bare sums and carries only `0 ≤ c`, `0 ≤ a`, `0 ≤ b`. The three sums are the lags `0`, `1`, `2` of
such a correlator.

`PeriodicSpectralForm`'s shape `λᵈ + λ⁴⁻ᵈ` is the `b = 1` case — a mode paired with the vacuum — and
at extent four it is not narrower than the general two-index transfer form: every unordered pair
`(a, b)` lands on the boundary surface `2ρ₁² = ρ₂² + ρ₀ρ₂`, at the cone ray the one-parameter curve
reaches at `λ = a/b`. `fourRepresentable_of_sums` and this theorem accordingly have the same three
conclusions and the same Cauchy–Schwarz proof.

DERIVED: the three `0`s are the signs of `c`, `a` and `b`. The exponents `4`, `3` and `2` are `d` and
`4 − d` at the lags `d = 0, 1, 2`: `a⁰b⁴ + b⁰a⁴`, `a¹b³ + b¹a³`, `a²b² + b²a²`, with `4` the period.
No magnitude is chosen. -/
theorem fourRepresentable_of_pairs {κ : Type*} [Fintype κ] (c a b : κ → ℝ)
    (hc : ∀ k, 0 ≤ c k) (ha : ∀ k, 0 ≤ a k) (hb : ∀ k, 0 ≤ b k) :
    FourRepresentable (∑ k, c k * (a k ^ 4 + b k ^ 4))
      (∑ k, c k * (a k * b k ^ 3 + b k * a k ^ 3))
      (∑ k, c k * (a k ^ 2 * b k ^ 2 + b k ^ 2 * a k ^ 2)) := by
  classical
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact Finset.sum_nonneg fun k _ => mul_nonneg (hc k) (by positivity)
  · exact Finset.sum_nonneg fun k _ => mul_nonneg (hc k) (by positivity)
  · refine Finset.sum_le_sum fun k _ => ?_
    refine mul_le_mul_of_nonneg_left ?_ (hc k)
    nlinarith [mul_nonneg (mul_nonneg (ha k) (hb k)) (sq_nonneg (a k - b k))]
  · -- Cauchy–Schwarz against `(√c · ab, √c · (a² + b²))`.
    set T : ℝ := ∑ k, c k * (a k ^ 2 * b k ^ 2) with hT
    set U : ℝ := ∑ k, c k * (a k ^ 4 + b k ^ 4) with hU
    have hsq : ∀ k, Real.sqrt (c k) * Real.sqrt (c k) = c k :=
      fun k => Real.mul_self_sqrt (hc k)
    have hcs := Finset.sum_mul_sq_le_sq_mul_sq Finset.univ
      (fun k => Real.sqrt (c k) * (a k * b k))
      (fun k => Real.sqrt (c k) * (a k ^ 2 + b k ^ 2))
    have hA : (∑ k, (Real.sqrt (c k) * (a k * b k)) * (Real.sqrt (c k) * (a k ^ 2 + b k ^ 2)))
        = ∑ k, c k * (a k * b k ^ 3 + b k * a k ^ 3) :=
      Finset.sum_congr rfl fun k _ => by
        linear_combination (a k * b k * (a k ^ 2 + b k ^ 2)) * hsq k
    have hB : (∑ k, (Real.sqrt (c k) * (a k * b k)) ^ 2) = T := by
      rw [hT]
      exact Finset.sum_congr rfl fun k _ => by
        linear_combination (a k ^ 2 * b k ^ 2) * hsq k
    have hC : (∑ k, (Real.sqrt (c k) * (a k ^ 2 + b k ^ 2)) ^ 2) = U + 2 * T := by
      rw [hT, hU, Finset.mul_sum, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun k _ => by
        linear_combination ((a k ^ 2 + b k ^ 2) ^ 2) * hsq k
    have h2T : (∑ k, c k * (a k ^ 2 * b k ^ 2 + b k ^ 2 * a k ^ 2)) = 2 * T := by
      rw [hT, Finset.mul_sum]
      exact Finset.sum_congr rfl fun k _ => by ring
    rw [hA, hB, hC] at hcs
    rw [h2T]
    nlinarith [hcs]

/-- **The region contains every weighted sum of the periodic two-term shape, from `w ≥ 0` and
`λ ≥ 0`.** The three sums `∑ w (1 + λ⁴)`, `∑ w (λ¹ + λ³)`, `∑ w (λ² + λ²)` satisfy
`FourRepresentable` given only `0 ≤ w k` and `0 ≤ lam k` pointwise. No upper bound on `λ` is
required. This is `fourRepresentable_of_pairs` at `b = 1`: the periodic two-term shape is a mode
paired with the vacuum.

The triple depends on `λ` only through `λ + 1/λ`, which `λ ↦ 1/λ` fixes, so a unit bound would cut
nothing away; `unit_bound_inert` states that.

DERIVED: the two `0`s are the signs of `w` and `lam`. The standalone `1` is the vacuum's decay factor
`1⁴`. The exponents `4`, `1`, `3`, `2` are the lags `d = 0, 1, 2` and their reflections `4 − d`, with
`4` the period. Nothing is chosen. -/
theorem fourRepresentable_of_sums {ι : Type*} [Fintype ι] (w lam : ι → ℝ)
    (hw : ∀ k, 0 ≤ w k) (hlam : ∀ k, 0 ≤ lam k) :
    FourRepresentable (∑ k, w k * (1 + lam k ^ 4)) (∑ k, w k * (lam k ^ 1 + lam k ^ 3))
      (∑ k, w k * (lam k ^ 2 + lam k ^ 2)) := by
  have h := fourRepresentable_of_pairs w lam (fun _ => (1 : ℝ)) hw hlam (fun _ => zero_le_one)
  have e0 : (∑ k, w k * (lam k ^ 4 + (1 : ℝ) ^ 4)) = ∑ k, w k * (1 + lam k ^ 4) :=
    Finset.sum_congr rfl fun k _ => by ring
  have e1 : (∑ k, w k * (lam k * (1 : ℝ) ^ 3 + (1 : ℝ) * lam k ^ 3))
      = ∑ k, w k * (lam k ^ 1 + lam k ^ 3) :=
    Finset.sum_congr rfl fun k _ => by ring
  have e2 : (∑ k, w k * (lam k ^ 2 * (1 : ℝ) ^ 2 + (1 : ℝ) ^ 2 * lam k ^ 2))
      = ∑ k, w k * (lam k ^ 2 + lam k ^ 2) :=
    Finset.sum_congr rfl fun k _ => by ring
  rwa [e0, e1, e2] at h

/-- **Every form at extent four lands in the region.** From `S : Spectral.PeriodicSpectralForm 4 ρ`,
the triple `(ρ 0, ρ 1, ρ 2)` is `FourRepresentable`. The proof reads `S.hrep` at the three
independent lags and applies `fourRepresentable_of_sums` to `S.w` and `S.lam`; only `S.hw` and
`S.hlam0` are consumed, and `S.hlam1` is not used.

DERIVED: `0`, `1`, `2` are lag indices and `4` the period, which is `N + 1` at the Clay aperture. -/
theorem fourRepresentable_of_form {ρ : Fin 4 → ℝ} (S : Spectral.PeriodicSpectralForm 4 ρ) :
    FourRepresentable (ρ 0) (ρ 1) (ρ 2) := by
  have e0 : ρ 0 = ∑ k, S.w k * (1 + S.lam k ^ 4) := by
    have h := S.hrep 0
    rw [val0] at h
    simpa using h
  have e1 : ρ 1 = ∑ k, S.w k * (S.lam k ^ 1 + S.lam k ^ 3) := by
    have h := S.hrep 1
    rw [val1] at h
    norm_num at h
    simpa using h
  have e2 : ρ 2 = ∑ k, S.w k * (S.lam k ^ 2 + S.lam k ^ 2) := by
    have h := S.hrep 2
    rw [val2] at h
    norm_num at h
    simpa using h
  rw [e0, e1, e2]
  exact fourRepresentable_of_sums S.w S.lam S.hw S.hlam0

/-- **Lag three is lag one, from the shape.** Any `Spectral.PeriodicSpectralForm 4 ρ` forces
`ρ 3 = ρ 1`, because `4 − 3 = 1` and `4 − 1 = 3`, so the two summands of `hrep` swap.

DERIVED: `1` and `3` are lag indices; `4` is the period. -/
theorem rho_three_eq_one {ρ : Fin 4 → ℝ} (S : Spectral.PeriodicSpectralForm 4 ρ) :
    ρ 3 = ρ 1 := by
  have h3 := S.hrep 3
  have h1 := S.hrep 1
  rw [val3] at h3
  rw [val1] at h1
  norm_num at h3 h1
  rw [h3, h1]
  exact Finset.sum_congr rfl fun k _ => by ring

/-! ## 3. Sufficiency — an explicit two-mode witness -/

/-- **The two-mode form.** Given nonnegative weights `w₀`, `w₁`, a decay factor `l ∈ [0, 1]`, and the
four lag identities `e0`–`e3` holding of `ρ`, a `Spectral.PeriodicSpectralForm 4 ρ` exists: one mode
at `λ = 0` carrying the contact term, one at `λ = l`. The arithmetic that produces `w₀, w₁, l` is
`exists_two_mode`; this lemma is the assembly only, stated on plain reals so that the index algebra
is separated from the root algebra.

DERIVED: the three `0`s in `0 ≤ w₀`, `0 ≤ w₁`, `0 ≤ l` are signs, and the `1` in `l ≤ 1` is the unit
bound `PeriodicSpectralForm.hlam1` requires. `0, 1, 2, 3` on the left of `e0`–`e3` are lag indices
and `4` is the period. The exponents `4, 1, 3, 2` in the right-hand sides are `d` and `4 − d` at
those lags. The mode count `2` appears in the proof's `Idx := Fin 2`, not in the statement. -/
private lemma two_mode_form {ρ : Fin 4 → ℝ} (w₀ w₁ l : ℝ)
    (hw₀ : 0 ≤ w₀) (hw₁ : 0 ≤ w₁) (hl0 : 0 ≤ l) (hl1 : l ≤ 1)
    (e0 : ρ 0 = w₀ + w₁ * (1 + l ^ 4))
    (e1 : ρ 1 = w₁ * (l ^ 1 + l ^ 3))
    (e2 : ρ 2 = w₁ * (l ^ 2 + l ^ 2))
    (e3 : ρ 3 = w₁ * (l ^ 3 + l ^ 1)) :
    Nonempty (Spectral.PeriodicSpectralForm 4 ρ) := by
  refine ⟨{ Idx := Fin 2
            w := ![w₀, w₁]
            lam := ![0, l]
            hw := ?_
            hlam0 := ?_
            hlam1 := ?_
            hrep := ?_ }⟩
  · intro k; fin_cases k
    · simpa using hw₀
    · simpa using hw₁
  · intro k; fin_cases k
    · simp
    · simpa using hl0
  · intro k; fin_cases k
    · simp
    · simpa using hl1
  · intro d
    fin_cases d
    · rw [show ((⟨0, by omega⟩ : Fin 4)) = (0 : Fin 4) from rfl, e0, Fin.sum_univ_two]
      norm_num
      try ring
    · rw [show ((⟨1, by omega⟩ : Fin 4)) = (1 : Fin 4) from rfl, e1, Fin.sum_univ_two]
      norm_num
      try ring
    · rw [show ((⟨2, by omega⟩ : Fin 4)) = (2 : Fin 4) from rfl, e2, Fin.sum_univ_two]
      norm_num
      try ring
    · rw [show ((⟨3, by omega⟩ : Fin 4)) = (3 : Fin 4) from rfl, e3, Fin.sum_univ_two]
      norm_num
      try ring

/-- **The two modes, from the two inequalities.** Given `0 < r₂`, `r₂ ≤ r₁` and
`2r₁² ≤ r₂² + r₀r₂`, there exist `w₀, w₁ ≥ 0` and `l ∈ [0, 1]` reproducing the three lags as
`r₀ = w₀ + w₁(1 + l⁴)`, `r₁ = w₁(l¹ + l³)`, `r₂ = w₁(l² + l²)`.

`c = r₁/r₂ ≥ 1` is `hord`, and it puts the smaller root `l = c − √(c² − 1)` of `l² − 2cl + 1 = 0` in
`(0, 1]`. That root's own equation is the only algebra the proof uses: it turns `l + l³` into
`2c·l²` and `1 + l⁴` into `(4c² − 2)·l²`, so the mode at `l` carries `((2c² − 1)r₂, r₁, r₂)` and the
contact weight is `w₀ = r₀ − (2c² − 1)r₂`. That weight is nonnegative exactly when `hq` holds. Two
modes suffice; the third free parameter a three-mode form would offer is never used.

`_h0` is carried only to match `FourRepresentable`'s field order and is not used: on `r₂ > 0` the
other two hypotheses force `r₀r₂ ≥ 2r₁² − r₂² ≥ r₂² > 0`.

DERIVED: in the hypotheses, the `0`s are signs, the coefficient `2` in `2 * r₁ ^ 2` is the pair
multiplicity at the self-paired lag and the exponents `2` are squares — all `FourRepresentable`'s
own. In the conclusion the `0`s are signs, the `1` in `l ≤ 1` is `hlam1`'s unit bound, the standalone
`1` is the vacuum's `l⁰`, and the exponents `4, 1, 3, 2` are `d` and `4 − d` at the lags
`d = 0, 1, 2`. No magnitude is chosen. -/
private lemma exists_two_mode {r₀ r₁ r₂ : ℝ} (_h0 : 0 ≤ r₀) (hpos : 0 < r₂)
    (hord : r₂ ≤ r₁) (hq : 2 * r₁ ^ 2 ≤ r₂ ^ 2 + r₀ * r₂) :
    ∃ w₀ w₁ l : ℝ, 0 ≤ w₀ ∧ 0 ≤ w₁ ∧ 0 ≤ l ∧ l ≤ 1 ∧
      r₀ = w₀ + w₁ * (1 + l ^ 4) ∧ r₁ = w₁ * (l ^ 1 + l ^ 3)
        ∧ r₂ = w₁ * (l ^ 2 + l ^ 2) := by
  have hr2ne : r₂ ≠ 0 := ne_of_gt hpos
  set c : ℝ := r₁ / r₂ with hc
  have hcr : c * r₂ = r₁ := by rw [hc]; field_simp
  have hc1 : 1 ≤ c := by rw [hc, le_div_iff₀ hpos]; linarith
  have hcc : 0 ≤ c ^ 2 - 1 := by nlinarith
  set s : ℝ := Real.sqrt (c ^ 2 - 1) with hs
  have hs2 : s ^ 2 = c ^ 2 - 1 := Real.sq_sqrt hcc
  have hs0 : 0 ≤ s := Real.sqrt_nonneg _
  set lam : ℝ := c - s with hlamdef
  have hlamc : lam * (c + s) = 1 := by rw [hlamdef]; nlinarith [hs2]
  have hcs0 : 0 < c + s := by nlinarith
  have hlam0 : 0 < lam := by nlinarith [hlamc, hcs0]
  have hlam1 : lam ≤ 1 := by
    have hsq : (c - 1) ^ 2 ≤ c ^ 2 - 1 := by nlinarith
    have hle : c - 1 ≤ s := by
      rw [hs]
      calc c - 1 = Real.sqrt ((c - 1) ^ 2) := (Real.sqrt_sq (by linarith)).symm
        _ ≤ Real.sqrt (c ^ 2 - 1) := Real.sqrt_le_sqrt hsq
    rw [hlamdef]; linarith
  -- the root's own equation, which is all the algebra below uses
  have hkey : lam ^ 2 + 1 = 2 * c * lam := by rw [hlamdef]; nlinarith [hs2]
  have hlamsq : 0 < lam ^ 2 := by positivity
  set w₁ : ℝ := r₂ / (2 * lam ^ 2) with hw1
  have hw1pos : 0 ≤ w₁ := by rw [hw1]; exact div_nonneg hpos.le (by linarith)
  have hE2 : w₁ * (lam ^ 2 + lam ^ 2) = r₂ := by rw [hw1]; field_simp; ring
  have hE1 : w₁ * (lam ^ 1 + lam ^ 3) = r₁ := by
    have hstep : w₁ * (lam ^ 1 + lam ^ 3) = (w₁ * (lam ^ 2 + lam ^ 2)) * c := by
      rw [hw1]; field_simp; nlinarith [hkey]
    rw [hstep, hE2]
    linarith [hcr]
  have hE0 : w₁ * (1 + lam ^ 4) = (2 * c ^ 2 - 1) * r₂ := by
    have hfour : 1 + lam ^ 4 = (4 * c ^ 2 - 2) * lam ^ 2 := by nlinarith [hkey]
    rw [hfour, hw1]; field_simp; ring
  have hw0pos : 0 ≤ r₀ - (2 * c ^ 2 - 1) * r₂ := by
    have hcsq : c ^ 2 * r₂ ^ 2 = r₁ ^ 2 := by rw [← hcr]; ring
    nlinarith [hcsq]
  clear_value w₁ lam s c
  exact ⟨r₀ - (2 * c ^ 2 - 1) * r₂, w₁, lam, hw0pos, hw1pos, hlam0.le, hlam1,
    by rw [hE0]; ring, hE1.symm, hE2.symm⟩

/-- **The region is attained.** `FourRepresentable (ρ 0) (ρ 1) (ρ 2)` together with the circle
symmetry `ρ 3 = ρ 1` produces a `Spectral.PeriodicSpectralForm 4 ρ`, with two modes: one at `λ = 0`
and one at `λ = c − √(c² − 1)`, `c = ρ(1)/ρ(2)`. Where `ρ(2) = 0` the quadratic forces `ρ(1) = 0` and
the form degenerates to the pure contact term of `Spectral2.contactForm`, recovered here as the
`w₁ = 0` member of the same two-mode family.

DERIVED: `0`, `1`, `2`, `3` are lag indices and `4` the period. The mode count `2` is what the proof
produces and does not appear in the statement. -/
theorem nonempty_of_fourRepresentable {ρ : Fin 4 → ℝ}
    (h : FourRepresentable (ρ 0) (ρ 1) (ρ 2)) (h3 : ρ 3 = ρ 1) :
    Nonempty (Spectral.PeriodicSpectralForm 4 ρ) := by
  obtain ⟨h0, h2, hord, hq⟩ := h
  rcases eq_or_lt_of_le h2 with hz | hpos
  · -- `ρ(2) = 0` forces `ρ(1) = 0`: the contact term, as the `w₁ = 0` member of the family.
    have hr1 : ρ 1 = 0 := by nlinarith [sq_nonneg (ρ 1)]
    refine two_mode_form (ρ := ρ) (ρ 0) 0 0 h0 le_rfl le_rfl zero_le_one ?_ ?_ ?_ ?_
    · norm_num
    · rw [hr1]; norm_num
    · rw [← hz]; norm_num
    · rw [h3, hr1]; norm_num
  · obtain ⟨w₀, w₁, l, hw₀, hw₁, hl0, hl1, e0, e1, e2⟩ :=
      exists_two_mode h0 hpos hord hq
    exact two_mode_form w₀ w₁ l hw₀ hw₁ hl0 hl1 e0 e1 e2 (by rw [h3, e1]; ring)

/-- **The characterisation.** At extent four, `Nonempty (Spectral.PeriodicSpectralForm 4 ρ)` holds
if and only if `FourRepresentable (ρ 0) (ρ 1) (ρ 2)` and `ρ 3 = ρ 1` — a semialgebraic condition on
three numbers plus one equation. Forward is `fourRepresentable_of_form` and `rho_three_eq_one`,
backward is `nonempty_of_fourRepresentable`.

DERIVED: `0`, `1`, `2`, `3` are lag indices; `4` is the period. -/
theorem four_iff {ρ : Fin 4 → ℝ} :
    Nonempty (Spectral.PeriodicSpectralForm 4 ρ)
      ↔ (FourRepresentable (ρ 0) (ρ 1) (ρ 2) ∧ ρ 3 = ρ 1) :=
  ⟨fun ⟨S⟩ => ⟨fourRepresentable_of_form S, rho_three_eq_one S⟩,
    fun h => nonempty_of_fourRepresentable h.1 h.2⟩

/-- **The unit bound on `λ` is inert at extent four.** If the three lags of `ρ` are given by sums
built from `w ≥ 0` and `λ ≥ 0` with no upper bound on `λ`, and `ρ 3 = ρ 1`, then a
`Spectral.PeriodicSpectralForm 4 ρ` exists — one whose own decay factors satisfy `λ ≤ 1`, since
`nonempty_of_fourRepresentable` builds it from a root in `(0, 1]`. So `hlam1` cuts nothing away at
this extent; the binding constraints are `w ≥ 0` and `λ ≥ 0`. The triple depends on `λ` only through
`λ + 1/λ`, which is invariant under `λ ↦ 1/λ`.

DERIVED: the two `0`s in the hypotheses are the signs of `w` and `lam`. `0`, `1`, `2`, `3` on the
left of `h0`–`h3` are lag indices and `4` is the period. The standalone `1` is the vacuum's `λ⁰`, and
the exponents `4, 1, 3, 2` are `d` and `4 − d` at the lags `d = 0, 1, 2`. -/
theorem unit_bound_inert {ι : Type*} [Fintype ι] (w lam : ι → ℝ)
    (hw : ∀ k, 0 ≤ w k) (hlam : ∀ k, 0 ≤ lam k) {ρ : Fin 4 → ℝ}
    (h0 : ρ 0 = ∑ k, w k * (1 + lam k ^ 4))
    (h1 : ρ 1 = ∑ k, w k * (lam k ^ 1 + lam k ^ 3))
    (h2 : ρ 2 = ∑ k, w k * (lam k ^ 2 + lam k ^ 2))
    (h3 : ρ 3 = ρ 1) :
    Nonempty (Spectral.PeriodicSpectralForm 4 ρ) := by
  refine nonempty_of_fourRepresentable ?_ h3
  rw [h0, h1, h2]
  exact fourRepresentable_of_sums w lam hw hlam

/-! ## 4. The shape facts do not separate the region -/

/-- **A conforming triple that is not ordered.** `TailRatio.TripleFacts` holds at `(4, 0, 4)` and
`FourRepresentable 4 0 4` fails, on its third conjunct `r₂ ≤ r₁`. So `ρ(2) ≤ ρ(1)` does not follow
from `TripleFacts`.

`ordered_is_what_nonneg_lam_buys` shows the same triple satisfies `hrep` at `w = (1, 1)`,
`λ = (1, −1)`, so what `ρ(2) ≤ ρ(1)` adds over the periodic shape is the positivity of the decay
factors rather than an analytic estimate.

DERIVED: `4` is `InfiniteVolume.wilsonCorrAt_abs_le_four`'s own uniform bound, quoted so the witness
sits inside `TripleFacts` rather than outside it. CHOSEN: `0` at lag one, the smallest value
`TripleFacts`'s nonnegativity permits, which makes the separation as wide as that premise set
allows. Neither is a threshold and neither is a constant of the theory. -/
theorem tripleFacts_not_ordered :
    MassGap.TailRatio.TripleFacts 4 0 4 ∧ ¬ FourRepresentable 4 0 4 := by
  refine ⟨⟨by norm_num, le_rfl, by norm_num, by norm_num, le_rfl, by norm_num, le_rfl⟩, ?_⟩
  rintro ⟨-, -, hord, -⟩
  norm_num at hord

/-- **A conforming, ordered triple that fails the quadratic.** `TailRatio.TripleFacts` holds at
`(4, 2, 1)`, the order `1 ≤ 2` holds, log-convexity holds with equality (`2² = 4 · 1`), and
`FourRepresentable 4 2 1` fails on its fourth conjunct: `2ρ(1)² ≤ ρ(2)² + ρ(0)·ρ(2)` reads `8 ≤ 5`.

So the quadratic does not follow from `TripleFacts` together with the order, and it is strictly
stronger than the log-convexity `LogConvex.corrClay_log_convex_at_extent_four` supplies — the
separation already occurs on the log-convex boundary.

DERIVED: `4` is `InfiniteVolume.wilsonCorrAt_abs_le_four`'s uniform bound, carried not chosen; the
exponent `2` is a square. CHOSEN: `2` and `1` at lags one and two, picked to put the triple exactly
on the log-convex boundary `ρ(1)² = ρ(0)·ρ(2)`, so that the separation is against `TripleFacts` at
its own extreme. They set no level and the statement is not about their magnitude. -/
theorem tripleFacts_not_quadratic :
    MassGap.TailRatio.TripleFacts 4 2 1 ∧ (1 : ℝ) ≤ 2 ∧ (2 : ℝ) ^ 2 = 4 * 1
      ∧ ¬ FourRepresentable 4 2 1 := by
  refine ⟨⟨by norm_num, by norm_num, by norm_num, by norm_num, le_rfl, by norm_num,
    by norm_num⟩, by norm_num, by norm_num, ?_⟩
  rintro ⟨-, -, -, hq⟩
  norm_num at hq

/-- **The order and the quadratic are independent.** At `(4, 0, 4)` the quadratic holds and the order
`r₂ ≤ r₁` fails; at `(4, 2, 1)` the order holds and the quadratic fails. So neither of
`FourRepresentable`'s last two conjuncts implies the other.

The statement is the four arithmetic facts themselves, on the two triples; it does not quantify over
triples and does not mention `TripleFacts`.

DERIVED: the values `4, 0, 4` and `4, 2, 1` are `tripleFacts_not_ordered`'s and
`tripleFacts_not_quadratic`'s witnesses, carried. The leading coefficient `2` and the exponents `2`
are `FourRepresentable`'s quadratic conjunct written out. -/
theorem missing_inequalities_independent :
    (2 * (0 : ℝ) ^ 2 ≤ (4 : ℝ) ^ 2 + 4 * 4 ∧ ¬ ((4 : ℝ) ≤ 0))
      ∧ ((1 : ℝ) ≤ 2 ∧ ¬ (2 * (2 : ℝ) ^ 2 ≤ (1 : ℝ) ^ 2 + 4 * 1)) := by
  refine ⟨⟨by norm_num, by norm_num⟩, ⟨by norm_num, by norm_num⟩⟩

/-- **`(4, 0, 4)` is reproduced by `w = (1, 1)` at `λ = (1, −1)`.** The statement is the three lag
identities `hrep` asks for at lags zero, one and two, written out as arithmetic over `ℝ`. What it
does not state, because it is not needed here, is the remaining `PeriodicSpectralForm` fields; of
those, `hlam0 : 0 ≤ lam k` is the one this assignment violates, at `λ = −1`.

Read with `tripleFacts_not_ordered`, this places the order `ρ(2) ≤ ρ(1)` at the positivity of the
decay factors rather than at a bound on a correlation.

DERIVED: `1` and `−1` are the two real solutions of `λ⁴ = 1`, so they are the decay factors a
period-four mode can carry while `|ρ|` stays flat; `4` and `0` are `tripleFacts_not_ordered`'s
witness, carried; the exponents `0, 1, 2, 3, 4` are the lags and their reflections `4 − d`. No
magnitude is chosen. -/
theorem ordered_is_what_nonneg_lam_buys :
    (4 : ℝ) = 1 * ((1 : ℝ) ^ (0 : ℕ) + (1 : ℝ) ^ 4) + 1 * ((-1 : ℝ) ^ (0 : ℕ) + (-1 : ℝ) ^ 4)
      ∧ (0 : ℝ) = 1 * ((1 : ℝ) ^ (1 : ℕ) + (1 : ℝ) ^ 3) + 1 * ((-1 : ℝ) ^ (1 : ℕ) + (-1 : ℝ) ^ 3)
      ∧ (4 : ℝ) = 1 * ((1 : ℝ) ^ (2 : ℕ) + (1 : ℝ) ^ 2)
          + 1 * ((-1 : ℝ) ^ (2 : ℕ) + (-1 : ℝ) ^ 2) := by
  refine ⟨by norm_num, by norm_num, by norm_num⟩

/-- **Both witnesses are positive-definite on `ℤ₄`.** A `ρ` on `ℤ₄` with `ρ(3) = ρ(1)` has the four
Fourier coefficients `ρ₀ + 2ρ₁ + ρ₂`, `ρ₀ − ρ₂` (twice) and `ρ₀ − 2ρ₁ + ρ₂`; positive-definiteness
as a function on the group is all four being nonnegative. The statement is the six resulting
inequalities, evaluated at `(4, 0, 4)` and `(4, 2, 1)`.

That is strictly more than `TripleFacts` carries, since `ρ₀ − ρ₂ ≥ 0` is `ρ(2) ≤ ρ(0)`, which
`TailRatio.no_lag_two_bound_from_triple` shows `TripleFacts` does not give. Since both witnesses
satisfy it, neither of `FourRepresentable`'s last two conjuncts follows from circle
positive-definiteness either. `(4, 0, 4)` is positive-definite on `ℤ₄` because it is the `λ = −1`
mode, which is what `hlam0` excludes.

DERIVED: the coefficients `1, 2, 1` and the signs are the `ℤ₄` characters at `p = 0, π/2, π`; the
values `4, 0, 4` and `4, 2, 1` are the two witnesses', carried; the `0`s are the signs asserted. No
magnitude is chosen. -/
theorem circle_psd_not_sufficient :
    ((0 : ℝ) ≤ 4 + 2 * 0 + 4 ∧ (0 : ℝ) ≤ 4 - 4 ∧ (0 : ℝ) ≤ 4 - 2 * 0 + 4)
      ∧ ((0 : ℝ) ≤ 4 + 2 * 2 + 1 ∧ (0 : ℝ) ≤ 4 - 1 ∧ (0 : ℝ) ≤ 4 - 2 * 2 + 1) := by
  refine ⟨⟨by norm_num, by norm_num, by norm_num⟩, ⟨by norm_num, by norm_num, by norm_num⟩⟩

/-! ## 5. The Wilson correlation at the Clay aperture -/

/-- **`FourRepresentable` of the Wilson triple at the Clay aperture.** A semialgebraic condition on
`(ρ(0), ρ(1), ρ(2))` where `ρ = wilsonCorrAt 3 β`, rather than a statement about an operator.

`wilsonSpectral_iff` makes it equivalent to `Complete.WilsonSpectral 3 β`; the circle symmetry that
the equivalence also needs is supplied by `MomentShape.wilsonCorrAt_neg`, through `wilson_lag_three`.
It holds at every `0 ≤ β`, by `LinkGram.wilson_lag_two_le_lag_one` and
`SlabQuadratic.wilson_quadratic`.

DERIVED: `3` is the Clay aperture, `0`, `1`, `2` the lag indices its extent-four period resolves. -/
def WilsonFourRepresentable (β : ℝ) : Prop :=
  FourRepresentable (MassGap.wilsonCorrAt 3 β 0) (MassGap.wilsonCorrAt 3 β 1)
    (MassGap.wilsonCorrAt 3 β 2)

/-- **Circle symmetry at extent four**: `wilsonCorrAt 3 β 3 = wilsonCorrAt 3 β 1`, at every real
coupling. This is `MomentShape.wilsonCorrAt_neg` at `−1 = 3` in `Fin 4`, the second half of what
`four_iff` needs.

DERIVED: `3` is both the aperture and the lag `−1` in `Fin 4`; `1` is the lag it folds onto. -/
theorem wilson_lag_three (β : ℝ) :
    MassGap.wilsonCorrAt 3 β 3 = MassGap.wilsonCorrAt 3 β 1 := by
  have h := MassGap.MomentShape.wilsonCorrAt_neg 3 β (1 : Fin 4)
  have hneg : (-(1 : Fin 4)) = (3 : Fin 4) := by decide
  rwa [hneg] at h

/-- **`WilsonSpectral 3 β` from `WilsonFourRepresentable β`.** The single hypothesis is the
semialgebraic condition on the three numbers; `nonempty_of_fourRepresentable` supplies the form and
`wilson_lag_three` supplies the circle symmetry it also needs.

The route to the form uses no operator, no GNS space and no `FiniteDimensional` hypothesis, unlike
`Transfer.periodicSpectralForm_of_transfer`, which requires one. Of `FourRepresentable`'s four
conjuncts, `0 ≤ ρ(0)` and `0 ≤ ρ(2)` come from `PlaqVariance.corrClay_zero_pos` and
`ReflectionStrong.corrClay_nonneg_even_lag`, through `TailRatio.triple_wilsonCorrAt`, and
`ρ(2) ≤ ρ(1)` and `2ρ(1)² ≤ ρ(2)² + ρ(0)·ρ(2)` come from `LinkGram.wilson_lag_two_le_lag_one` and
`SlabQuadratic.wilson_quadratic`. By `fourRepresentable_of_pairs` those last two are what a finite
transfer matrix supplies.

DERIVED: `3` is the Clay aperture, the only numeral in the statement. -/
theorem wilsonSpectral_of_representable {β : ℝ} (h : WilsonFourRepresentable β) :
    MassGap.WilsonSpectral 3 β :=
  nonempty_of_fourRepresentable h (wilson_lag_three β)

/-- **The equivalence at the Clay aperture**: `WilsonSpectral 3 β` holds if and only if
`WilsonFourRepresentable β`. Forward is `fourRepresentable_of_form` applied to a chosen member of the
`Nonempty`; backward is `wilsonSpectral_of_representable`.

DERIVED: `3` is the Clay aperture, the only numeral in the statement. -/
theorem wilsonSpectral_iff {β : ℝ} :
    MassGap.WilsonSpectral 3 β ↔ WilsonFourRepresentable β :=
  ⟨fun h => fourRepresentable_of_form h.some, wilsonSpectral_of_representable⟩

/-- **The free point is inside the region.** `WilsonFourRepresentable 0` — the Wilson triple at zero
coupling satisfies all four conjuncts.

It is `Spectral2.wilsonSpectral_at_zero_coupling` transported through `wilsonSpectral_iff`, so it has
the same producer rather than an independent one. What it records is that the equivalence is not
vacuous on the left: the coupling at which `WilsonSpectral 3 β` is established does land inside
`FourRepresentable`.

DERIVED: the only numeral in the statement is the `0`, the free coupling. `3` is the Clay aperture
and sits inside `WilsonFourRepresentable`'s definition. -/
theorem wilsonFourRepresentable_at_zero : WilsonFourRepresentable 0 :=
  (wilsonSpectral_iff).mp (MassGap.Spectral2.wilsonSpectral_at_zero_coupling 2)

section Audit
#print axioms FourRepresentable
#print axioms fourRepresentable_le
#print axioms fourRepresentable_const
#print axioms fourRepresentable_of_pairs
#print axioms fourRepresentable_of_sums
#print axioms fourRepresentable_of_form
#print axioms rho_three_eq_one
#print axioms nonempty_of_fourRepresentable
#print axioms four_iff
#print axioms unit_bound_inert
#print axioms tripleFacts_not_ordered
#print axioms tripleFacts_not_quadratic
#print axioms missing_inequalities_independent
#print axioms ordered_is_what_nonneg_lam_buys
#print axioms circle_psd_not_sufficient
#print axioms WilsonFourRepresentable
#print axioms wilson_lag_three
#print axioms wilsonSpectral_of_representable
#print axioms wilsonSpectral_iff
#print axioms wilsonFourRepresentable_at_zero
end Audit

end MassGap.SpectralFour
